/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Contact Editor");
gchar *s = N_("Business Fax");
gchar *s = N_("Home");
gchar *s = N_("Business");
gchar *s = N_("Mobile");
gchar *s = N_("Email");
gchar *s = N_("\tFull Name...");
gchar *s = N_("Job Title:");
gchar *s = N_("Company:");
gchar *s = N_("File As:");
gchar *s = N_("Web page address:");
gchar *s = N_("Contacts...");
gchar *s = N_("Categories...");
gchar *s = N_("This is the mailing address");
gchar *s = N_("A_ddress...");
gchar *s = N_("Business");
gchar *s = N_("General");
gchar *s = N_("Department:");
gchar *s = N_("Office:");
gchar *s = N_("Profession:");
gchar *s = N_("Nickname:");
gchar *s = N_("Spouse's name:");
gchar *s = N_("Directory Server:");
gchar *s = N_("Email alias:");
gchar *s = N_("Address:");
gchar *s = N_("Birthday:");
gchar *s = N_("Assistant's name:");
gchar *s = N_("Manager's name:");
gchar *s = N_("Anniversary:");
gchar *s = N_("Call Now");
gchar *s = N_("Internet Free-Busy");
gchar *s = N_("Online NetMeeting settings");
gchar *s = N_("Details");
gchar *s = N_("Activities");
gchar *s = N_("Certificates");
gchar *s = N_("All Fields");
gchar *s = N_("Add");
gchar *s = N_("Delete");
gchar *s = N_("Phone Types");
gchar *s = N_("New phone type");
gchar *s = N_("New phone type");
gchar *s = N_("Add");
