/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Check Full Name");
gchar *s = N_("Title:");
gchar *s = N_("First:");
gchar *s = N_("Middle:");
gchar *s = N_("Last:");
gchar *s = N_("Suffix:");
gchar *s = N_("\n"
              "Mr.\n"
              "Mrs.\n"
              "Dr.\n"
              "");
gchar *s = N_("\n"
              "Senior\n"
              "Junior\n"
              "II\n"
              "III\n"
              "Esquire\n"
              "");
gchar *s = N_("Show this again when name is incomplete or unclear");
