/*
 * Translatable strings file generated by extract-ui.
 * Add this file to your project's POTFILES.in
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Add");
gchar *s = N_("Delete");
gchar *s = N_("Edit");
gchar *s = N_("Edit Filters");
gchar *s = N_("Edit VFolders");
gchar *s = N_("Filter Rules");
gchar *s = N_("Remove");
gchar *s = N_("Virtual Folders");
gchar *s = N_("vFolder Sources");
