/*
 * Wombat interfaces.
 *
 * Copyright (C) 2000, 2001, 2002, Ximian, Inc.
 */

#include <Bonobo.idl>

module GNOME {
module Evolution {

	interface WombatClient : Bonobo::Unknown {
		string getPassword (in string prompt, in string key);
		void   forgetPassword (in string key);
	};

	interface Config : Bonobo::Unknown {
	};

	interface WombatInterfaceCheck : Bonobo::Unknown {
		readonly attribute string interfaceVersion;
	};
};
};
