/*
 * Wombat interfaces.
 *
 * Copyright (C) 2000, 2001, 2002, Ximian, Inc.
 */

#include <Bonobo.idl>

module GNOME {
module Evolution {

	interface Config {
	};

	interface WombatInterfaceCheck : Bonobo::Unknown {
		readonly attribute string interfaceVersion;
	};
};
};
