/*
 * The Evolution Personal Organization Server.
 *
 * Copyright 2000, Helix Code, Inc.
 */

module GNOME {
module Evolution {

	interface WombatClient {
		string getPassword (in string prompt, in string key);
		void   forgetPassword (in string key);
	};

	interface Config {

	};
};
};
