/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
 * Interface for the Evolution components.
 *
 * Authors:
 *   Ettore Perazzoli <ettore@helixcode.com>
 *
 * Copyright (C) 2000 Helix Code, Inc.
 */

#include <Bonobo.h>

module Evolution {
	interface Shell;

	struct FolderType {
		string name;
		string icon_name;
	};

	typedef sequence<FolderType> FolderTypeList;

	interface ShellComponent : Bonobo::Unknown {
		readonly attribute FolderTypeList supported_types;

		/* FIXME can we use an attribute here?  */
		exception AlreadyOwned {};
		void set_owner (in Shell shell)
			raises (AlreadyOwned);

		exception NotOwned {};
		void unset_owner ()
			raises (NotOwned);

		exception NotFound {};
		Bonobo::Control create_view (in string physical_uri)
			raises (NotFound);
	};
};
