/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
 * Interface for the Evolution's StorageSetView control.
 *
 * Authors:
 *   Ettore Perazzoli <ettore@ximian.com>
 *
 * Copyright (C) 2000, 2001, 2002 Ximian, Inc.
 */

#include <Bonobo.idl>

module GNOME {
module Evolution {
	interface StorageSetViewListener {
		void notifyFolderSelected (in string uri);
		void notifyFolderToggled (); 
	};

	/* FIXME: Maybe we should have a generic Bonobo::Listener interface.  */
	interface StorageSetView : Bonobo::Unknown {
		exception AlreadyListening {};
		exception NotFound {};

		attribute boolean showFolders;
		attribute boolean showCheckboxes;

		attribute FolderList checkedFolders;

		void addListener (in StorageSetViewListener listener)
			raises (AlreadyListening);

		void removeListener (in StorageSetViewListener listener)
			raises (NotFound);
	};
};
};
