/*
 * CORBA interface for the Evolution shell
 *
 * Authors:
 *   Miguel de Icaza (miguel@kernel.org)
 *
 * (C) 2000 Helix Code, Inc.
 */
#include <Bonobo.idl>

module Evolution {
	interface Shell : Bonobo::Unknown {
		enum NewType {
			APPOINTMENT,
			MEETING_REQUEST,
			TASK,
			TASK_REQUEST,
			CONTACT,
			MAIL_MESSAGE,
			DISTRIBUTION_LIST,
			JOURNAL_ENTRY,
			NOTE
		};
		
		void new (in NewType type);
	};
};

