/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
 * Interface for saving configuration information.
 *
 * Authors:
 *   Ettore Perazzoli <ettore@ximian.com>
 *
 * Copyright (C) 2000, 2001 Ximian, Inc.
 */

#include <Bonobo.idl>

module GNOME {
module Evolution {

	interface Session : Bonobo::Unknown {
		exception Failed {};

		/**
		 * saveConfiguration:
		 * @prefix: A configuration path prefix.
		 *
		 * Save the current configuration at the specified @prefix.
		 * The component can use any path starting by @prefix for its
		 * keys.
		 */
		void saveConfiguration (in string prefix)
			raises (Failed);

		/**
		 * loadConfiguration:
		 * @prefix: A configuration path prefix.
		 *
		 * Load the saved configuration at the specified @prefix.
		 */
		void loadConfiguration (in string prefix)
			raises (Failed);
	};
	
};
};
