/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
 * CORBA interface for the Evolution shell.
 *
 * Authors:
 *   Ettore Perazzoli <ettore@ximian.com>
 *
 * Copyright (C) 2000, 2001 Ximian, Inc.
 */

#include <Bonobo.idl>

#include <Evolution-common.idl>

#include <Evolution-Activity.idl>
#include <Evolution-Component.idl>
#include <Evolution-ConfigControl.idl>
#include <Evolution-Session.idl>
#include <Evolution-ShellComponent.idl>
#include <Evolution-ShellComponentDnd.idl>
#include <Evolution-Offline.idl>
#include <Evolution-ShellView.idl>
#include <Evolution-Shortcuts.idl>
#include <Evolution-Storage.idl>
#include <Evolution-StorageSetView.idl>
#include <Evolution-Shell.idl>
#include <Evolution-Wizard.idl>
