/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
 * Interface for the Evolution shell views.
 *
 * Authors:
 *   Ettore Perazzoli <ettore@ximian.com>
 *
 * Copyright (C) 2000, 2001 Ximian, Inc.
 */

#include <Bonobo.idl>

module GNOME {
module Evolution {
	interface ShellView : Bonobo::Unknown {
		void setMessage        (in string message,
					in boolean busy);
		void unsetMessage      ();
		void changeCurrentView (in string uri);
		void setTitle          (in string title);
		void setFolderBarLabel (in string text);
		void showSettings      ();
	};
};
};
