/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
 * Interface for the Evolution local storage.
 *
 * Authors:
 *   Ettore Perazzoli <ettore@ximian.com>
 *
 * Copyright (C) 2000, 2001 Ximian, Inc.
 */

#include <Bonobo.idl>

module GNOME {
module Evolution {
	interface LocalStorage : Evolution::Storage {
		/**
		 * update_folder:
		 * @path: Path of a folder within the storage.
		 * @display_name: Name to be displayed in the tree view for
		 * this folder
		 * @highlighted: Whether or not to highlight the name.
		 *
		 * Set the name to display for the folder at the specified
		 * @path.
		 */
		void updateFolder (in string path,
				   in string display_name,
				   in boolean highlighted);
	};
};
};
