/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
 * Storage interface for the Evolution shell.
 *
 * Authors:
 *   Ettore Perazzoli <ettore@helixcode.com>
 *
 * Copyright (C) 2000 Helix Code, Inc.
 */

#include <Bonobo.h>

module Evolution {
	struct Folder {
		string type;
		string description;
		string display_name;
		string physical_uri;
		boolean highlighted;
	};

	interface Storage;
	interface StorageListener;

	interface Storage : Bonobo::Unknown {
		exception AlreadyListening {};
		exception NotFound {};

		attribute string name;

		void add_listener (in StorageListener listener)
			raises (AlreadyListening);

		void remove_listener (in StorageListener listener)
			raises (NotFound);
	};

	interface StorageListener {
		exception Exists {};
		exception NotFound {};

		void destroyed ();

		/* FIXME exceptions don't make much sense here...  */

		void new_folder (in string path, in Folder folder)
			raises (Exists);

		void update_folder (in string path, in string display_name,
				    in boolean highlighted)
			raises (NotFound);

		void removed_folder (in string path)
			raises (NotFound);
	};

	interface StorageRegistry : Bonobo::Unknown {
		exception Exists {};
		exception NotFound {};

		StorageListener register_storage (in Storage storage, in string name)
			raises (Exists);

		void unregister_storage (in string name)
			raises (NotFound);
	};
};
