/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Page Setup:");
gchar *s = N_("Style name:");
gchar *s = N_("Preview:");
gchar *s = N_("Options");
gchar *s = N_("Include:");
gchar *s = N_("Sections:");
gchar *s = N_("Immediately follow each other");
gchar *s = N_("Letter tabs on side");
gchar *s = N_("Headings for each letter");
gchar *s = N_("Start on a new page");
gchar *s = N_("Number of columns:");
gchar *s = N_("Blank forms at end:");
gchar *s = N_("Fonts");
gchar *s = N_("Font...");
gchar *s = N_("Font...");
gchar *s = N_("Headings");
gchar *s = N_("10 pt. Tahoma");
gchar *s = N_("Body");
gchar *s = N_("8 pt. Tahoma");
gchar *s = N_("Shading");
gchar *s = N_("Print using gray shading");
gchar *s = N_("Format");
gchar *s = N_("Paper");
gchar *s = N_("Type:");
gchar *s = N_("label26");
gchar *s = N_("Dimensions:");
gchar *s = N_("Width:");
gchar *s = N_("Height:");
gchar *s = N_("Paper source:");
gchar *s = N_("Margins");
gchar *s = N_("Top:");
gchar *s = N_("Bottom:");
gchar *s = N_("Left:");
gchar *s = N_("Right:");
gchar *s = N_("Page");
gchar *s = N_("Size:");
gchar *s = N_("label26");
gchar *s = N_("Dimensions:");
gchar *s = N_("Width:");
gchar *s = N_("Height:");
gchar *s = N_("Orientation");
gchar *s = N_("Portrait");
gchar *s = N_("Landscape");
gchar *s = N_("Paper");
gchar *s = N_("Font...");
gchar *s = N_("Header");
gchar *s = N_("Footer:");
gchar *s = N_("Font...");
gchar *s = N_("Reverse on even pages");
gchar *s = N_("Header/Footer");
