/*
 * Translatable strings file generated by extract-ui.
 * Add this file to your project's POTFILES.in
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Description:");
gchar *s = N_("LDAP Server:");
gchar *s = N_("Name:");
gchar *s = N_("Port Number:");
gchar *s = N_("Root DN:");
