N_("Aarhus")
N_("Abakan")
N_("Abbotsford")
N_("Aberdeen")
N_("Abha")
N_("Abilene")
N_("Abingdon")
N_("Abu Dhabi")
N_("Abu Dhabi - Bateen")
N_("Acajutla")
N_("Acapulco")
N_("Acarigua")
N_("Adak")
N_("Adana")
N_("Adana/Incirlik")
N_("Adelaide")
N_("Aden")
N_("Adrar")
N_("Aeroparque")
N_("Aeropuerto del Norte")
N_("Afonsos")
N_("Africa")
N_("Afyon")
N_("Agen")
N_("Aguascaliantes")
N_("Ahmadabad")
N_("Ahwaz")
N_("Ainsworth")
N_("Air Force")
N_("Ajaccio/Campo dell'Oro")
N_("Akeno Ab")
N_("Akita Airport")
N_("Akron")
N_("Akrotiri")
N_("Alabama")
N_("Al Ahsa")
N_("Al Ain")
N_("Alamogordo")
N_("Alamosa")
N_("Alaska")
N_("Al Baha")
N_("Albania")
N_("Albany")
N_("Albenga")
N_("Alberta")
N_("Alborg")
N_("Albuquerque")
N_("Alderney")
N_("Alesund")
N_("Alexandria")
N_("Alexandria-Esler")
N_("Alexandria/Nouzha")
N_("Alexandroupolis")
N_("Algeria")
N_("Alghero")
N_("Algona")
N_("Alicante")
N_("Alice")
N_("Alice Springs")
N_("Al-Jouf")
N_("Allentown")
N_("Alliance")
N_("Alma")
N_("Almeria")
N_("Alpena")
N_("Al Qaysumah")
N_("Alta")
N_("Altamira")
N_("Alton")
N_("Altoona")
N_("Alturas")
N_("Altus")
N_("Amami Airport")
N_("Amapala")
N_("Amarillo")
N_("Amasya")
N_("Ambler")
N_("Amelia")
N_("Amendola")
N_("Ames")
N_("Amritsar")
N_("Amsterdam")
N_("Anadyr")
N_("Anaktuvuk")
N_("Anapa")
N_("Anchorage")
N_("Anchorage - Elmendorf AFB")
N_("Ancona")
N_("Andahuayla")
N_("Anderson")
N_("Andoya")
N_("Andravida")
N_("Andrews AFB")
N_("Angleton")
N_("Aniak")
N_("Ankara/Esenboga")
N_("Ankara/Etimesgut")
N_("Annaba")
N_("Ann Arbor")
N_("Annette")
N_("Anniston")
N_("Antalya")
N_("Antartica")
N_("Antigo")
N_("Antigua")
N_("Antigua and Barbuda")
N_("Antofagasta")
N_("Antwerpen/Deurne")
N_("Aomori Airport")
N_("Apalachicola")
N_("Appleton")
N_("Aquadilla")
N_("Aracaju")
N_("Arad")
N_("Arar")
N_("Araxos")
N_("Arcata")
N_("Ardmore")
N_("Arequipa")
N_("Argentina")
N_("Arica")
N_("Arizona")
N_("Arkansas")
N_("Arkhangelsk")
N_("Arlington")
N_("Artigas")
N_("Asahikawa Ab")
N_("Asahikawa Airport")
N_("Ashburnam")
N_("Asheville")
N_("Ashfield")
N_("Ashiya Ab")
N_("Ashland")
N_("Asia")
N_("Aspen")
N_("Asswan")
N_("Astoria")
N_("Astrakhan")
N_("Asturias")
N_("Asuncion")
N_("Athens")
N_("Athinai")
N_("Atlanta")
N_("Atlantic")
N_("Atlantic City")
N_("Atsugi US NAS")
N_("Auburn")
N_("Auckland")
N_("Augsburg")
N_("Augusta")
N_("Aurora")
N_("Austin")
N_("Australasia")
N_("Australia")
N_("Austria")
N_("Avalon")
N_("Aviano")
N_("Ayacucho")
N_("Bage")
N_("Bagotville")
N_("Bahamas")
N_("Bahia Blanca")
N_("Bahias de Huatulco")
N_("Bahrain")
N_("Baker City")
N_("Bakersfield")
N_("Bale-Mulhouse")
N_("Balikesir")
N_("Balikesir/Bandirma")
N_("Ball Mountain")
N_("Baltimore")
N_("Baltimore-Glen Burnie")
N_("Banak")
N_("Bandarabbass")
N_("Bangor")
N_("Baracoa")
N_("Barbers Point")
N_("Barcelona")
N_("Bardufoss")
N_("Bar Harbor")
N_("Bari")
N_("Bariloche")
N_("Barinas")
N_("Barking Sand")
N_("Barksdale")
N_("Barnaul")
N_("Barquisimeto")
N_("Barranquilla/Ernestocortissoz")
N_("Barrow")
N_("Barter Island")
N_("Bartlesville")
N_("Bartow")
N_("Bastia")
N_("Batesville")
N_("Batman")
N_("Baton Rouge")
N_("Battle Creek")
N_("Battle Mountain")
N_("Bauru")
N_("Bayamo")
N_("Bayreuth")
N_("Beatrice")
N_("Beaufort")
N_("Beaumont")
N_("Beaumont-Port Arthur")
N_("Beauvais-Tille")
N_("Beauvechain")
N_("Beckley")
N_("Bedford")
N_("Beijing")
N_("Beirut")
N_("Beja")
N_("Belem")
N_("Belfast/Aldergrove")
N_("Belfast/Harbour")
N_("Belgium")
N_("Belgorod")
N_("Belize")
N_("Belleville")
N_("Bellingham")
N_("Belmar-Farmingdale")
N_("Belo Horizonte")
N_("Belo Horizonte Apt")
N_("Bemidji")
N_("Benbecula")
N_("Benina")
N_("Benton Harbor")
N_("Bentonville")
N_("Beograd")
N_("Bergamo")
N_("Bergen")
N_("Bergstrom AFB")
N_("Berlevag")
N_("Berlin")
N_("Berlin-Tegel")
N_("Berlin-Tempelhof")
N_("Bern")
N_("Bethel")
N_("Bethlehem Airport")
N_("Bettles")
N_("Beverly")
N_("Biarritz-Bayonne")
N_("Bicycle Lake")
N_("Biggin Hill")
N_("Big Piney")
N_("Big River Lake")
N_("Bilbao")
N_("Billings")
N_("Billund")
N_("Binghamton")
N_("Birmingham")
N_("Bisha")
N_("Bishop")
N_("Bismark")
N_("Blackpool")
N_("Blagoveschensk")
N_("Blanding")
N_("Block Island")
N_("Bloemfontein J. B. M. Hertzog ")
N_("Bloomington")
N_("Blue Canyon")
N_("Bluefield")
N_("Bluefields")
N_("Blythe")
N_("Boa Vista")
N_("Bocas del Toro")
N_("Bodo")
N_("Bogota/Eldorado")
N_("Boise")
N_("Bolivia")
N_("Bologna")
N_("Bolzano")
N_("Bombay/Santacruz")
N_("Boone")
N_("Bordeaux")
N_("Borger")
N_("Bornholm")
N_("Boscombe Down")
N_("Bosnia-Herzegovina")
N_("Boston")
N_("Boulmer")
N_("Bourges")
N_("Bournemouth")
N_("Bowling Green")
N_("Bozeman")
N_("Bradford")
N_("Bradshaw Field")
N_("Brainerd")
N_("Brasilia")
N_("Brasschaat")
N_("Bratislava")
N_("Bratsk")
N_("Braunschweig")
N_("Brazil")
N_("Bremen")
N_("Bremerton")
N_("Brest")
N_("Bridgeport")
N_("Brindisi")
N_("Brisbane")
N_("Bristol")
N_("British Columbia")
N_("Brno")
N_("Broadus")
N_("Broken Bow")
N_("Bronnoysund")
N_("Brookings")
N_("Brooksville")
N_("Broome")
N_("Brownsville")
N_("Brunswick")
N_("Brussels-National Airport")
N_("Bryansk")
N_("Bryce Canyon")
N_("Bucaramanga/Palonegro")
N_("Bucuresti")
N_("Bucuresti-Otopeni")
N_("Budapest")
N_("Buffalo")
N_("Bulgaria")
N_("Bullfrog")
N_("Burbank")
N_("Burgas")
N_("Burley")
N_("Burlington")
N_("Burnet")
N_("Burns")
N_("Bursa")
N_("Burwell")
N_("Butte")
N_("Caen-Carpiquet")
N_("Cagliari")
N_("Cairns")
N_("Cairo")
N_("Calabozo")
N_("Calcutta/Dum Dum")
N_("Caldwell")
N_("Calgary")
N_("Cali/Alfonso Bonillaaragon")
N_("Caliente")
N_("California")
N_("Calvi-Ste-Catherine")
N_("Camaguey")
N_("Camarillo")
N_("Cambridge")
N_("Cameron")
N_("Camiri")
N_("Campeche")
N_("Campinas")
N_("Campo")
N_("Campo Grande")
N_("Camp Stanley/H-207")
N_("Canaan")
N_("Canada")
N_("Canarias/Fuerteventura")
N_("Canarias/Gran Canaria")
N_("Canarias/Hierro")
N_("Canarias/Lanzarote")
N_("Canarias/La Palma")
N_("Canarias/Tenerife Norte")
N_("Canarias/Tenerife Sur")
N_("Canberra")
N_("Cancun")
N_("Cannes-Mandelieu")
N_("Cantwell")
N_("Cape Girardeau")
N_("Cape Hatteras")
N_("Cape Lisburne")
N_("Cape Newenham")
N_("Cape Romanzoff")
N_("Cape Town D. F. Malan ")
N_("Capitan Corbeta")
N_("Capo Mele")
N_("Caracas La Carlota")
N_("Caracas Maiquetia")
N_("Caravelas")
N_("Carbondale")
N_("Cardiff")
N_("Caribou")
N_("Carlisle")
N_("Carlsbad")
N_("Carroll")
N_("Cartagena/Rafael Nunez")
N_("Casa Granda")
N_("Cascade")
N_("Casper")
N_("Catacamas")
N_("Catania")
N_("Cayman Islands")
N_("Cayo Largo del Sur")
N_("Cazaux")
N_("Cecil NAS")
N_("Cedar City")
N_("Cedar Rapids")
N_("Central and South America")
N_("Cervia")
N_("Chacarita")
N_("Chadron")
N_("Challis")
N_("Chamberlain")
N_("Chambery")
N_("Champaign")
N_("Chandalar Lake")
N_("Chandler")
N_("Chania")
N_("Chanute")
N_("Chariton")
N_("Charleroi-Brussels South")
N_("Charles City")
N_("Charleston")
N_("Charlotte")
N_("Charlottesville")
N_("Chatham")
N_("Chattanooga")
N_("Cheboksary")
N_("Cheju")
N_("Chelyabinsk")
N_("Chengdu")
N_("Cherbourg")
N_("Cherry Point")
N_("Chetumal")
N_("Cheyenne")
N_("Chiang Kai Shek")
N_("Chia Tung")
N_("Chiayi")
N_("Chicago-DuPage")
N_("Chicago-Lakefront")
N_("Chicago-Midway")
N_("Chicago-O'Hare")
N_("Chichijima")
N_("Chiclayo")
N_("Chico")
N_("Chicopee Falls")
N_("Chievres")
N_("Chihhang")
N_("Chihuahua")
N_("Childress")
N_("Chile")
N_("China Lake")
N_("Chinandega")
N_("Chinmem/Shatou")
N_("Chino")
N_("Chippewa County")
N_("Chita")
N_("Chitose Ab")
N_("Chitose ASDF")
N_("Chofu Airport")
N_("Choluteca")
N_("Chongju Ab")
N_("Christchurch")
N_("Christmas Island")
N_("Chulitna")
N_("Churchill")
N_("Churchill Falls")
N_("Cincinnati")
N_("Circle City")
N_("Ciudad Bolivar")
N_("Ciudad del Carmen")
N_("Ciudad Juarez")
N_("Ciudad Obregon")
N_("Ciudad Victoria")
N_("Clarinda")
N_("Clarion")
N_("Clarksburg")
N_("Clayton")
N_("Clayton Lake")
N_("Clermont-Ferrand")
N_("Cleveland")
N_("Cleveland/Cuyahoga")
N_("Cleveland-Lakefront")
N_("Clinton")
N_("Clovis-Cannon AFB")
N_("Cobija")
N_("Cochabamba")
N_("Cocoa Beach")
N_("Cocos Island")
N_("Cody")
N_("Coeur d'Alene")
N_("Cold Bay")
N_("Colima")
N_("College Station")
N_("Colmar-Meyenheim")
N_("Colombia")
N_("Colonia")
N_("Colorado")
N_("Colorado Springs")
N_("Columbia")
N_("Columbia-McEntire")
N_("Columbus")
N_("Columbus-Fort Benning")
N_("Columbus-Gahanna")
N_("Columbus-OSU")
N_("Columbus-W Point-Starkville")
N_("Colville")
N_("Comodoro Rivadavia")
N_("Comox")
N_("Conceicao Do Araguaia")
N_("Concepcion")
N_("Concord")
N_("Concordia")
N_("Connaught")
N_("Connecticut")
N_("Conroe")
N_("Constantine")
N_("Copper Harbor")
N_("Cordoba")
N_("Cordova")
N_("Cork")
N_("Coro")
N_("Corona")
N_("Corpus Christi")
N_("Corpus Christi NAS")
N_("Corrientes")
N_("Corsicana")
N_("Cortez")
N_("Corumba")
N_("Costa Rica")
N_("Cotulla")
N_("Council Bluffs")
N_("Coventry")
N_("Covington")
N_("Cozumel")
N_("Craig")
N_("Cranfield")
N_("Crescent City")
N_("Creston")
N_("Crestview")
N_("Croatia")
N_("Cross City")
N_("Crossville")
N_("Crotone")
N_("Cuba")
N_("Cuba Awrs")
N_("Cuernavaca")
N_("Cuiaba")
N_("Culdrose")
N_("Culiacan")
N_("Cumana")
N_("Cumberland")
N_("Curitiba")
N_("Curitiba Apt")
N_("Custer")
N_("Cut Bank")
N_("Cuzco")
N_("Cyprus")
N_("Czech Republic")
N_("Dagali")
N_("Daggett")
N_("Dalhart")
N_("Dalian")
N_("Dallas-Addison")
N_("Dallas-Fort Worth")
N_("Dallas-Love Field")
N_("Dallas-Redbird")
N_("Da Nang")
N_("Danbury")
N_("Danville")
N_("Dar-El-Beida")
N_("Davenport")
N_("David")
N_("Dawadmi")
N_("Dayton")
N_("Daytona Beach")
N_("Dayton-Fairborn")
N_("Dayton-South Airport")
N_("Dead Horse")
N_("Deauville-Saint-Gatien")
N_("Decatur")
N_("Decimomannu")
N_("Decorah")
N_("Deelen")
N_("Dekalb/Peachtree")
N_("Delaware")
N_("Del Bajio")
N_("Del Rio")
N_("Delta")
N_("Deming")
N_("Den Helder/De Kooy")
N_("Denison")
N_("Denmark")
N_("Denton")
N_("Denver")
N_("Denver-Aurora")
N_("Denver-Broomfield")
N_("Denver-Cherry Knolls")
N_("Desert Rock")
N_("Des Moines")
N_("Destin")
N_("Detroit")
N_("Detroit Lakes")
N_("Detroit-Taylor")
N_("Detroit/Ypsilanti")
N_("Devils Lake")
N_("Devils Lake (2)")
N_("Dhahran")
N_("Dickinson")
N_("Dijon")
N_("Dillingham")
N_("Dillon")
N_("Dinard")
N_("District of Columbia")
N_("Diyarbakir")
N_("Dobbiaco")
N_("Dodge City")
N_("Doha")
N_("Dole")
N_("Dominican Republic")
N_("Dongsha")
N_("Dongshi")
N_("Don Torcuato")
N_("Dortmund-Wickede")
N_("Dothan")
N_("Douglas")
N_("Dover")
N_("Dresden-Klotzsche")
N_("Drummond")
N_("Dubai")
N_("Dubbo")
N_("Dublin")
N_("Du Bois")
N_("Dubrovnik")
N_("Dubuque")
N_("Dugway")
N_("Duluth")
N_("Dundee")
N_("Durango")
N_("Durango Awrs")
N_("Durazno")
N_("Durban Louis Botha ")
N_("Dusseldorf")
N_("Dutch Harbor")
N_("Dyersburg")
N_("Eagle")
N_("Eagle Range")
N_("East London")
N_("East Midlands")
N_("East St Louis")
N_("Eau Claire")
N_("Ecuador")
N_("Edinburgh")
N_("Edmonton")
N_("Edmonton/Villeneuve")
N_("Eduardo Gomes International")
N_("Edwards AFB")
N_("Egilsstadir")
N_("Eglin")
N_("Eglington/Londonderry")
N_("Egypt")
N_("Eindhoven")
N_("Ekofisk")
N_("Elazig")
N_("El Centro")
N_("El Dorado")
N_("Elefsis")
N_("Elfin Cove")
N_("Elizabeth City")
N_("Elk City")
N_("Elkhart")
N_("Elkins")
N_("Elko")
N_("Elmira")
N_("El Monte")
N_("El Paso")
N_("El Salvador")
N_("El Salvador Int.")
N_("Elsenborn")
N_("Ely")
N_("Emmonak")
N_("Emporia")
N_("Enid")
N_("Enid/Woodring")
N_("Enosburg Falls")
N_("Ephrata")
N_("Ercan")
N_("Erie")
N_("Erzurum")
N_("Esbjerg")
N_("Escanaba")
N_("Esfahan")
N_("Eskisehir")
N_("Estherville")
N_("Estonia")
N_("Eugene")
N_("Eureka")
N_("Europe")
N_("Evanston")
N_("Evansville")
N_("Everett")
N_("Evergreen")
N_("Evreux-Fauville")
N_("Exeter")
N_("Ezeiza")
N_("Fagernes")
N_("Fairbanks")
N_("Fairchild")
N_("Fairfield")
N_("Fairmont")
N_("Fallon")
N_("Falls City")
N_("Falmouth-Otis AFB")
N_("Farbanks/Eielson AFB")
N_("Fargo")
N_("Farmingdale")
N_("Farmington")
N_("Farmville")
N_("Faro")
N_("Fayetteville")
N_("Feng Nin")
N_("Fergus Falls")
N_("Fernando De Noronha")
N_("Ferrara")
N_("Figari")
N_("Findlay")
N_("Finland")
N_("Firenze")
N_("Fitchburg")
N_("Flagstaff")
N_("Flint")
N_("Flippin")
N_("Florence")
N_("Florennes")
N_("Flores")
N_("Florianopolis")
N_("Florida")
N_("Floro")
N_("Fond Du Lac")
N_("Forde/Bringeland")
N_("Forli")
N_("Formosa")
N_("Fortaleza")
N_("Fort Belvoir")
N_("Fort Benning")
N_("Fort Bragg")
N_("Fort Campbell")
N_("Fort Carson")
N_("Fort Collins")
N_("Fort Collins/Lovel")
N_("Fort Dodge")
N_("Fort Drum")
N_("Fort Eustis")
N_("Fort Greely/Allen AAF")
N_("Fort Huachuca")
N_("Fort Knox")
N_("Fort Lauderdale")
N_("Fort Lauderdale (International)")
N_("Fort Leonard")
N_("Fort Lewis")
N_("Fort Madison")
N_("Fort Meade")
N_("Fort Myers (Page Field)")
N_("Fort Myers (Southwest Florida International)")
N_("Fort Polk-Leesville")
N_("Fort Riley")
N_("Fort Sill")
N_("Fort Smith")
N_("Fort Stewart")
N_("Fort Stockton")
N_("Fort Wayne")
N_("Fort Worth-Alliance")
N_("Fort Worth-Meacham")
N_("Fort Worth NAS")
N_("Fourchon")
N_("Foz Do Iguacu")
N_("France")
N_("Frankfort")
N_("Frankfurt/Main")
N_("Franklin")
N_("Fredericton")
N_("Freeport")
N_("Frenchville")
N_("Fresno")
N_("Fresno-Chandler")
N_("Friday Harbor")
N_("Friedrichshafen")
N_("Frigg")
N_("Frontone")
N_("Frosinone")
N_("Fryeburg")
N_("Fujairah")
N_("Fuji Ab")
N_("Fukue Airport")
N_("Fukui Airport")
N_("Fukuoka Airport")
N_("Fullerton")
N_("Funchal")
N_("FYR Macedonia")
N_("Gadsden")
N_("Gage")
N_("Gainesville")
N_("Galax-Hillsville")
N_("Galbraith Lake")
N_("Galeao")
N_("Galena")
N_("Galesburg")
N_("Gallup")
N_("Galveston")
N_("Gambell")
N_("Gander")
N_("Garden City")
N_("Gary")
N_("Gassim")
N_("Gatineau")
N_("Gaziantep")
N_("Gdansk")
N_("Geneve")
N_("Genova")
N_("George Airport")
N_("Georgetown")
N_("Georgia")
N_("Germany")
N_("Ghardaia")
N_("Ghedi")
N_("Gibraltar")
N_("Gifu Ab")
N_("Gila Bend")
N_("Gillette")
N_("Gilze-Rijen")
N_("Gioia del Colle")
N_("Girona")
N_("Gizan")
N_("Glasgow")
N_("Glendive")
N_("Glens Falls")
N_("Goiania")
N_("Goldsboro")
N_("Goodland")
N_("Goose Bay")
N_("Goteborg (Landvetter)")
N_("Goteborg (Save)")
N_("Granada")
N_("Grand Canyon")
N_("Grand Cayman")
N_("Grand Forks")
N_("Grand Island")
N_("Grand Isle")
N_("Grand Junction")
N_("Grand Marais")
N_("Grand Rapids")
N_("Grandview")
N_("Grangeville")
N_("Grants")
N_("Graz")
N_("Great Falls")
N_("Greece")
N_("Greeley")
N_("Green Bay")
N_("Green River")
N_("Greensboro")
N_("Greenville")
N_("Greenville-Spartanburg")
N_("Greenwood")
N_("Grenoble-Saint-Geoirs")
N_("Griffiss AFB")
N_("Groningen")
N_("Grosseto")
N_("Groton")
N_("Guadalajara")
N_("Guadalupe Pass")
N_("Guanare")
N_("Guangzhou")
N_("Guantanamo")
N_("Guarany")
N_("Guaratingueta")
N_("Guarulhos")
N_("Guatemala")
N_("Guayaquil/Simon Bolivar")
N_("Guaymas")
N_("Guernsey")
N_("Guidonia")
N_("Gulfport")
N_("Gulkana")
N_("Gullfax C")
N_("Gunnison")
N_("Gunnison (2)")
N_("Guriat")
N_("Gustavus")
N_("Guymon")
N_("Habana")
N_("Hachijojima Airport")
N_("Hachinohe Ab")
N_("Hafr Al-Batin")
N_("Hagerstown")
N_("Hail")
N_("Hailey-Sun Valley")
N_("Haines")
N_("Haiti")
N_("Hakodate Airport")
N_("Halifax")
N_("Hamamatsu Ab")
N_("Hamburg")
N_("Hamburg-Finkenwerder")
N_("Hamilton")
N_("Hammerfest")
N_("Hampton")
N_("Hanamaki Airport")
N_("Hancock")
N_("Hangzhou")
N_("Hanksville")
N_("Hannover")
N_("Ha Noi")
N_("Harbor Beach")
N_("Harlingen")
N_("Harlowton")
N_("Harrisburg")
N_("Harrison")
N_("Harstad/Narvik/Evenes")
N_("Hartford")
N_("Hassi-Messaoud")
N_("Hastings")
N_("Haugesund")
N_("Havre")
N_("Hawaii")
N_("Hawthorne")
N_("Hayden")
N_("Hayes River")
N_("Hays")
N_("Hayward")
N_("Healy River")
N_("Helena")
N_("Helsinki")
N_("Henderson")
N_("Hengchun")
N_("Hermosillo")
N_("Hibbing")
N_("Hickory")
N_("Hill City")
N_("Hillsboro")
N_("Hilo")
N_("Hinesville")
N_("Hiroshima Airport")
N_("Hobart")
N_("Hobbs")
N_("Ho Chi Minh")
N_("Hodeidah")
N_("Hof")
N_("Hoffman")
N_("Hofu Ab")
N_("Hohenems")
N_("Holguin")
N_("Homer")
N_("Homestead AFB")
N_("Hondo")
N_("Honduras")
N_("Hong Kong")
N_("Honningsvag")
N_("Honolulu")
N_("Hoonah")
N_("Hoquiam")
N_("Hot Springs")
N_("Houghton Lake")
N_("Houlton")
N_("Houma")
N_("Houston-Bush")
N_("Houston-Clover")
N_("Houston-Ellington Field")
N_("Houston-Hobby")
N_("Houston-Hooks")
N_("Howard AFB")
N_("Hsinchu")
N_("Huanuco")
N_("Huehuetenango")
N_("Hulien")
N_("Humberside")
N_("Hungary")
N_("Huntington")
N_("Huntsville")
N_("Hurlburt")
N_("Huron")
N_("Hutchinson")
N_("Hyakuri Ab")
N_("Hyannis")
N_("Hyderabad")
N_("Hyeres-Le Palyvestre")
N_("Iasi")
N_("Ibiza")
N_("Iceland")
N_("Ichikawa")
N_("Idaho")
N_("Idaho Falls")
N_("Iguazu")
N_("Iki Airport")
N_("Ilan")
N_("Iliamna")
N_("Illinois")
N_("Imperial")
N_("Imperial (2)")
N_("Imperial Beach")
N_("In Amenas")
N_("India")
N_("Indiana")
N_("Indianapolis")
N_("Indian Springs")
N_("Innsbruck")
N_("International Falls")
N_("Intracoastal")
N_("Inverness")
N_("Inyokern")
N_("Iowa")
N_("Iowa City")
N_("Iqaluit")
N_("Iquique/Diego Arac")
N_("Iquitos")
N_("Iraklion")
N_("Iran, Islamic Republic of")
N_("Ireland")
N_("Iron Mountain")
N_("Ironwood")
N_("Iruma Ab")
N_("Islamabad")
N_("Isle of Man")
N_("Islip")
N_("Istanbul")
N_("Itaituba")
N_("Italy")
N_("Ithaca")
N_("Iwakuni MCAS")
N_("Iwojima")
N_("Ixtapa")
N_("Izmir/Adnan Menderes")
N_("Izmir/Cigli")
N_("Izmit")
N_("Izumo Airport")
N_("Jackson")
N_("Jacksonville")
N_("Jacksonville-Craig Airport")
N_("Jacksonville NAS")
N_("Jaffrey")
N_("Jamaica")
N_("Jamestown")
N_("Janesville")
N_("Jan Smuts")
N_("Japan")
N_("Jeddah King Abdul Aziz International Airport")
N_("Jefferson City")
N_("Jerez")
N_("Jersey")
N_("Jinotega")
N_("Johan A. Pengel")
N_("Johnstown")
N_("Jonesboro")
N_("Jonkoping")
N_("Joplin")
N_("Jordan")
N_("Juanjui")
N_("Juan Santamaria")
N_("Juigalpa")
N_("Jujuy")
N_("Juliaca")
N_("Junction")
N_("Juneau")
N_("Kadena Ab")
N_("Kagoshima Airport")
N_("Kahului")
N_("Kailua-Kona")
N_("Kake")
N_("Kalamata")
N_("Kalamazoo")
N_("Kalispell")
N_("Kamigoto")
N_("Kaneohe")
N_("Kangshan")
N_("Kanoya Ab")
N_("Kansai International Airport")
N_("Kansas")
N_("Kansas City")
N_("Kansas City-Gladstone")
N_("Kaohsiung")
N_("Karachi")
N_("Karup")
N_("Kassel-Calden")
N_("Kasumigaura Ab")
N_("Kasuminome Ab")
N_("Katowice")
N_("Kavala")
N_("Kayseri")
N_("Kazan")
N_("Kearney")
N_("Keene")
N_("Kefallinia")
N_("Keflavik")
N_("Kenai")
N_("Kenosha")
N_("Kentucky")
N_("Keokuk")
N_("Kerkira")
N_("Kerman")
N_("Ketchikan")
N_("Key West")
N_("Key West NAS")
N_("Khabarovsk")
N_("Khamis Mushait")
N_("Kikai Island")
N_("Killeen")
N_("Killeen-Ft Hood")
N_("Killeen-Gray AAF")
N_("King Khaled International Airport")
N_("Kingman")
N_("King Salmon")
N_("Kingston")
N_("Kingsville")
N_("Kinloss")
N_("Kinston")
N_("Kirkenes")
N_("Kirksville")
N_("Kiruna")
N_("Kisarazu Ab")
N_("Kishineu")
N_("Kitakyushu Airport")
N_("Klagenfurt")
N_("Klamath Falls")
N_("Klawock")
N_("Kleine Brogel")
N_("Kliningrad")
N_("Knoxville")
N_("Knoxville-Downtown")
N_("Kobenhavn/Kastrup")
N_("Kobenhavn/Roskilde")
N_("Kochi Airport")
N_("Kodiak")
N_("Kogalniceanu")
N_("Kogalym")
N_("Koksijde")
N_("Kolding/Vandrup")
N_("Koln/Bonn")
N_("Komatsu Ab")
N_("Komatsujima Ab")
N_("Konya")
N_("Korea, Democratic People's Republic of")
N_("Korea, Republic of")
N_("Kos")
N_("Kotzebue")
N_("Kozani")
N_("Krakow")
N_("Krasnodar")
N_("Krasnoyarsk")
N_("Kristiansand/Kjevik")
N_("Kristiansund/Kvernberget")
N_("Kumamoto Airport")
N_("Kunming")
N_("Kushiro Airport")
N_("Kuwait")
N_("La Ceiba")
N_("Laconia")
N_("La Coruna")
N_("La Crosse")
N_("La Esperanza")
N_("Lafayette")
N_("La Grande")
N_("Lahaina")
N_("Lahore")
N_("Lajes")
N_("La Junta")
N_("Lake Charles")
N_("Lake Hood")
N_("Lakehurst")
N_("Lakeland")
N_("Lake Tahoe")
N_("Lakeview")
N_("Lamar")
N_("La Mesa")
N_("Lamezia")
N_("Lamoni")
N_("Lampedusa")
N_("Lanai")
N_("Lancaster")
N_("Lander")
N_("Langebaanweg")
N_("Langley AFB")
N_("Lannion")
N_("Lansing")
N_("Lanzhou")
N_("La Paz")
N_("La Paz/Alto")
N_("Laramie")
N_("Laredo")
N_("Larnaka")
N_("La Romana")
N_("Las Americas")
N_("Las Tunas")
N_("Las Vegas")
N_("Latina")
N_("Latrobe")
N_("Latvia")
N_("Laughlin")
N_("Laurel")
N_("La Verne")
N_("Lawrence")
N_("Lawton")
N_("Leadville")
N_("Learmouth")
N_("Lebanon")
N_("Lecce")
N_("Leeds and Bradford")
N_("Leesburg")
N_("Leeuwarden")
N_("Le Havre-Octeville")
N_("Leipzig-Schkeuditz")
N_("Leknes")
N_("Le Mans")
N_("Le Marine")
N_("Lemmon")
N_("Lemoore")
N_("Leticia/Vasquez Cobo")
N_("Le Touquet")
N_("Leuchars")
N_("Lewisburg")
N_("Lewiston")
N_("Lewistown")
N_("Lexington")
N_("Liberal")
N_("Liberia")
N_("Libya")
N_("Lichtenburg")
N_("Lidgerwood")
N_("Liege")
N_("Lihue")
N_("Lille-Lesquin")
N_("Lima-Callao")
N_("Limnos")
N_("Limoges")
N_("Limon")
N_("Lincoln")
N_("Linz")
N_("Lisboa")
N_("Lista")
N_("Litchfield")
N_("Lithuania")
N_("Little Rock")
N_("Little Rock AFB")
N_("Livermore")
N_("Liverpool")
N_("Livingston")
N_("Ljubljana")
N_("Logan")
N_("Lolland Falster")
N_("Lompoc")
N_("London")
N_("London/City")
N_("London/Gatwick")
N_("London/Heathrow")
N_("London/Stansted")
N_("Londrina")
N_("Lone Rock")
N_("Long Beach")
N_("Longview")
N_("Lorient-Lann-Bihoue")
N_("Los Alamos")
N_("Los Angeles")
N_("Los Mochis")
N_("Lossiemouth")
N_("Louisville")
N_("Louisville-Standiford Field")
N_("Lousiana")
N_("Lovelock")
N_("Lubbock")
N_("Lubeck-Blankensee")
N_("Lufkin")
N_("Lugano")
N_("Luqa")
N_("Luton")
N_("Luxembourg")
N_("Luxeuil")
N_("Luxor")
N_("Lynchburg")
N_("Lyneham")
N_("Lyon-Bron")
N_("Lyon-Satolas")
N_("Maastricht")
N_("Macae")
N_("Macapa")
N_("Maceio")
N_("Macon")
N_("Madinah")
N_("Madison")
N_("Madras/Minambakkam")
N_("Madrid (Barajas)")
N_("Madrid (Cuatro Vientos)")
N_("Magadan")
N_("Magdalena")
N_("Maine")
N_("Makhachkala")
N_("Makkah")
N_("Makung")
N_("Malad City")
N_("Malaga")
N_("Malatya")
N_("Maldonado/Punta Est")
N_("Malmo/Sturup")
N_("Malta")
N_("Mammoth Lakes")
N_("Managua")
N_("Manassas")
N_("Manaus")
N_("Manchester")
N_("Mangilsan Ab")
N_("Manhattan")
N_("Manisa")
N_("Manistee")
N_("Manitoba")
N_("Manitowoc")
N_("Mankato")
N_("Mansfield")
N_("Manta")
N_("Manzanillo")
N_("Maraba")
N_("Maracaibo-La Chinita")
N_("Maracay-B.A.Sucre")
N_("Marathon")
N_("Mar Del Plata")
N_("Margarita")
N_("Marianna")
N_("Marib")
N_("Maribor")
N_("Marietta")
N_("Marino di Ravenna")
N_("Marion")
N_("Marion-Wytheville")
N_("Marquette")
N_("Marseille-Provence")
N_("Marseilles")
N_("Marshall")
N_("Marshalltown")
N_("Marshfield")
N_("Marte")
N_("Marthas Vineyard")
N_("Martinsburg")
N_("Martinsville")
N_("Maryland")
N_("Marysville")
N_("Marysville-Beale AFB")
N_("Mashhad")
N_("Masirah")
N_("Mason City")
N_("Massachusetts")
N_("Massena")
N_("Matamoros")
N_("Matsumoto Airport")
N_("Matsushima Ab")
N_("Matsuyama Airport")
N_("Mattoon")
N_("Mayaguez")
N_("Mayport")
N_("Mazatlan")
N_("Mazu")
N_("McAlester")
N_("McAllen")
N_("McCall")
N_("McCarthy")
N_("McClellan")
N_("McComb")
N_("McCook")
N_("McGrath")
N_("Mc Gregor")
N_("Meacham")
N_("Medford")
N_("Medicine Lodge")
N_("Mehamn")
N_("Mekoryuk")
N_("Melbourne")
N_("Melfa")
N_("Melilla")
N_("Memambetsu Airport")
N_("Memphis")
N_("Memphis-NAS")
N_("Mendoza")
N_("Mene Grande")
N_("Menominee")
N_("Menorca")
N_("Merced")
N_("Merida")
N_("Meridian")
N_("Meridian-Lauderdale")
N_("Merril Field")
N_("Mersa Matruh")
N_("Mesa-Falcon Field")
N_("Metabaru Ab")
N_("Metz-Frescaty")
N_("Mexicali")
N_("Mexico")
N_("Miami")
N_("Miami-Kendall")
N_("Miami-Opa Locka")
N_("Michigan")
N_("Middle East")
N_("Middleton Island")
N_("Middletown")
N_("Midland")
N_("Miho Ab")
N_("Milano/Linate")
N_("Milano/Malpensa")
N_("Miles City")
N_("Milford")
N_("Millinocket")
N_("Millville")
N_("Milton")
N_("Milwaukee")
N_("Milwaukee-Timmerman")
N_("Minamitorishima")
N_("Minatitlan")
N_("Minchumina")
N_("Mineralnye Vody")
N_("Mineral Wells")
N_("Minneapolis")
N_("Minneapolis [2]")
N_("Minneapolis [3]")
N_("Minnesota")
N_("Minocqua")
N_("Minot")
N_("Minot AFB")
N_("Misawa Ab")
N_("Mississippi")
N_("Missoula")
N_("Missouri")
N_("Mitchell")
N_("Mitilini")
N_("Miyakejima Airport")
N_("Miyazaki Airport")
N_("Moa")
N_("Mobile Downtown")
N_("Mobile Regional Airport")
N_("Mobridge")
N_("Modesto")
N_("Mo I Rana")
N_("Mojave")
N_("Molde")
N_("Moldova")
N_("Moline-Quad Cities")
N_("Molokai")
N_("Mombetsu Airport")
N_("Monchengladbach")
N_("Monclova")
N_("Moncton")
N_("Monida")
N_("Monpellier-Mediterrannee")
N_("Monroe")
N_("Montague")
N_("Montana")
N_("Mont-de-Marsan")
N_("Monte Argentario")
N_("Monte Bisbino")
N_("Monte Calamita")
N_("Monte Cimone")
N_("Montego Bay")
N_("Monte Malanotte")
N_("Monterey")
N_("Monterrey")
N_("Monte Scuro")
N_("Monte Terminillo")
N_("Montevideo/Carrasco")
N_("Montgomery")
N_("Montgomery-Maxwell AFB")
N_("Monticello")
N_("Montpelier")
N_("Montreal Dorval")
N_("Montreal Mirabel")
N_("Montreal Saint-Hubert")
N_("Montrose")
N_("Montrose (2)")
N_("Morelia")
N_("Morgantown")
N_("Moriarty")
N_("Morocco")
N_("Morristown")
N_("Moscow Domodedovo")
N_("Moscow Sheremetyevo")
N_("Moses Lake")
N_("Mosinee")
N_("Mosjoen")
N_("Moultrie")
N_("Mountain Home")
N_("Mountain View")
N_("Mount Clemens")
N_("Mount Holly")
N_("Mount Shasta")
N_("Mount Vernon")
N_("Mount Wilson")
N_("Mt Washington")
N_("Mugla/Dalaman")
N_("Muir")
N_("Mullan")
N_("Mullen")
N_("Munchen")
N_("Muncie")
N_("Munster/Osnabruck")
N_("Murcia")
N_("Murmansk")
N_("Mus")
N_("Muscatine")
N_("Muscle Shoals")
N_("Muskegon")
N_("Mykonos")
N_("Myrtle Beach")
N_("Nabesna/Devil Mt.")
N_("Nacogdoches")
N_("Nagasaki Airport")
N_("Nagoya Airport")
N_("Nagpur Sonegaon")
N_("Naha Airport")
N_("Najran")
N_("Nakashibetsu Airport")
N_("Nalchik")
N_("Namsos")
N_("Nancy-Essey")
N_("Nancy-Ochey")
N_("Nankishirahama Airport")
N_("Nanning")
N_("Nantes Adlantique")
N_("Nantucket")
N_("Napa")
N_("Naples")
N_("Napoli")
N_("Narvik")
N_("Nasa Shuttle")
N_("Nashua")
N_("Nashville")
N_("Nassau")
N_("Natal")
N_("Natchez")
N_("Nawabshah")
N_("Nebraska")
N_("Needles")
N_("Nenana")
N_("Netherlands")
N_("Neuquen")
N_("Nevada")
N_("Newark")
N_("New Bedford")
N_("New Bern")
N_("New Braunfels")
N_("New Brunswick")
N_("Newburgh")
N_("Newcastle")
N_("New Delhi/Palam")
N_("Newfoundland")
N_("New Hampshire")
N_("New Haven")
N_("New Iberia")
N_("New Jersey")
N_("New Mexico")
N_("New Orleans")
N_("New Orleans-Lakefront")
N_("New Orleans NAS")
N_("Newport")
N_("Newport News")
N_("New Port Richey")
N_("New River")
N_("New Tokyo International Airport")
N_("Newton")
N_("New York")
N_("New York-JFK Arpt")
N_("New York-La Guardia")
N_("New Zealand")
N_("Niagara Falls")
N_("Nicaragua")
N_("Nice-Cote d'Azur")
N_("Niigata Airport")
N_("Nimes-Garons")
N_("Nipawin")
N_("Nis")
N_("Nizhny Novgorod")
N_("N Las Vegas")
N_("N Myrtle Beach")
N_("Nogales")
N_("Nome")
N_("Norfolk")
N_("Norfolk Island")
N_("Norfolk NAS")
N_("Norrkoping")
N_("North Adams")
N_("North Bend")
N_("North Carolina")
N_("North Conway")
N_("North Dakota")
N_("Northeast Philadelphia")
N_("North Kingstown")
N_("North Platte")
N_("Northway")
N_("Northwest Territories")
N_("Norway")
N_("Norwich")
N_("Norwood")
N_("Notodden")
N_("Novara/Cameri")
N_("Nova Scotia")
N_("Novosibirsk")
N_("Nueva Gerona")
N_("Nueva Ocotepeque")
N_("Nuevo Laredo")
N_("Nurnberg")
N_("Nyutabaru Ab")
N_("Oahu")
N_("Oak Harbor")
N_("Oakland")
N_("Oaxaca")
N_("Oberpfaffenhofen")
N_("Obihiro Airport")
N_("Ocala")
N_("Oceanside")
N_("Odense")
N_("Oelwen")
N_("Ogden")
N_("Ogden-Hill AFB")
N_("Ogdensburg")
N_("Ohio")
N_("Ohrid")
N_("Oita Airport")
N_("Ojika Island")
N_("Okayama Airport")
N_("Oki Airport")
N_("Okinoerabu")
N_("Oklahoma")
N_("Oklahoma City")
N_("Oklahoma City-Bethany")
N_("Oklahoma City-Midwest City")
N_("Okushiri Island")
N_("Olathe")
N_("Olathe/Ind.")
N_("Olbia")
N_("Olympia")
N_("Omaha")
N_("Omaha-Bellevue")
N_("Omak")
N_("Oman")
N_("Ominato Ab")
N_("Omsk")
N_("O'Neill")
N_("Ontario")
N_("Oostende")
N_("Oran")
N_("Oran/Es Senia")
N_("Orange")
N_("Orange City")
N_("Ord-Sharp")
N_("Oregon")
N_("Orenburg")
N_("Orland")
N_("Orlando")
N_("Orlando (Orlando International)")
N_("Orsta-Volda")
N_("Oruro")
N_("Osaka International Airport")
N_("Osan Ab")
N_("Oscoda")
N_("Oseberg A")
N_("Oshima Airport")
N_("Oshkosh")
N_("Oslo/Gardenmoen")
N_("Ostrava")
N_("Ottawa")
N_("Ottumwa")
N_("Owensboro")
N_("Owyhee")
N_("Oxford")
N_("Oxnard")
N_("Ozark")
N_("Ozuki Ab")
N_("Paderborn-Haxterberg")
N_("Padova")
N_("Paducah")
N_("Paekado")
N_("Paengnyongdo Ab")
N_("Paganella")
N_("Page")
N_("Pakistan")
N_("Pa Kuei/Bakuai")
N_("Palacios")
N_("Palermo")
N_("Palma de Mallorca")
N_("Palmdale")
N_("Palmer")
N_("Palm Springs")
N_("Palo Alto")
N_("Pamplona")
N_("Panama")
N_("Panama City")
N_("Pantelleria")
N_("Papa")
N_("Paphos")
N_("Paraguay")
N_("Paris")
N_("Paris/Charles De Gaulle")
N_("Paris/Le Bourget")
N_("Paris/Orly")
N_("Parkersburg")
N_("Pasco")
N_("Paso De Los Libres")
N_("Paso Robles")
N_("Passo dei Giovi")
N_("Passo della Cisa")
N_("Passo Resia")
N_("Passo Rolle")
N_("Patna")
N_("Patterson")
N_("Patuxent River")
N_("Pau/Pyrenees")
N_("Paxson")
N_("Paysandu")
N_("Payson")
N_("Pellston")
N_("Pelotas")
N_("Pendleton")
N_("Pennsylvania")
N_("Penn Yan")
N_("Pensacola")
N_("Pensacola NAS")
N_("People's Republic of China")
N_("Peoria")
N_("Pequot Lakes")
N_("Pereira/Matecana")
N_("Perm")
N_("Perpignan-Rivesaltes")
N_("Perry-Foley")
N_("Perth")
N_("Peru")
N_("Perugia")
N_("Pescara")
N_("Petersburg")
N_("Petropavlovsk-Kamchatsky")
N_("Petrozavodsk")
N_("Philadelphia")
N_("Philip")
N_("Philipsburg")
N_("Phillips")
N_("Phoenix")
N_("Phoenix-Deer Valley")
N_("Phoenix-Goodyear")
N_("Phoenix-Luke AFB")
N_("Piacenza")
N_("Pian Rosa")
N_("Piedras Negras")
N_("Pierre")
N_("Pietersburg")
N_("Pikeville")
N_("Pine Bluff")
N_("Pingtung North")
N_("Pingtung South")
N_("Pirassununga")
N_("Pisa")
N_("Pisco")
N_("Pittsburgh")
N_("Pittsburgh-West Mifflin")
N_("Plattsburg")
N_("Plovdiv")
N_("Plymouth")
N_("Pocatello")
N_("Pocos De Caldas")
N_("Podgorica")
N_("Podgorica Titograd")
N_("Pohang Ab")
N_("Point Hope")
N_("Point Lay")
N_("Point Mugu")
N_("Point Piedras Blanca")
N_("Poitiers")
N_("Poland")
N_("Pompano Beach")
N_("Ponca City")
N_("Ponce")
N_("Ponta Pora")
N_("Pontiac")
N_("Pope AFB")
N_("Poplar Bluff")
N_("Poprad")
N_("Port Alexander")
N_("Port Alsworth")
N_("Port Angeles")
N_("Port-Au-Prince")
N_("Port Elizabeth")
N_("Porterville")
N_("Port Hardy")
N_("Port Hedland")
N_("Port Heiden")
N_("Portland")
N_("Porto")
N_("Porto Alegre")
N_("Porto Alegre Apt")
N_("Portoroz")
N_("Porto Santo")
N_("Porto Velho")
N_("Port Said")
N_("Portsmouth")
N_("Portugal")
N_("Posadas")
N_("Potosi")
N_("Poughkeepsie")
N_("Pownal")
N_("Poza Rica")
N_("Poznan")
N_("Praha")
N_("Pratica di Mare")
N_("Prescott")
N_("Presidente Prudente")
N_("Presque Isle")
N_("Prestwick")
N_("Pretoria")
N_("Preveza")
N_("Price-Carbon")
N_("Pristina")
N_("Providence")
N_("Provincetown")
N_("Provo")
N_("Pskov")
N_("Pucallpa")
N_("Pudahuel")
N_("Puebla")
N_("Pueblo")
N_("Puerto Barrios")
N_("Puerto Cabezas")
N_("Puerto Escondido")
N_("Puerto Lempira")
N_("Puerto Limon")
N_("Puerto Maldonado")
N_("Puerto Montt")
N_("Puerto Plata")
N_("Puerto Rico")
N_("Puerto Suarez")
N_("Puerto Vallarta")
N_("Pula")
N_("Pullman")
N_("Punta Arenas")
N_("Punta Cana")
N_("Punta Gorda")
N_("Puntilla Lake")
N_("Pusan/Kimhae")
N_("Pyongtaek Ab")
N_("Pyongyang")
N_("Qatar")
N_("Quantico")
N_("Quebec")
N_("Quebec City")
N_("Queretaro")
N_("Quillayute")
N_("Quimper")
N_("Quincy")
N_("Quito/Mariscal Sucre")
N_("Rabat")
N_("Raduzhny")
N_("Rafha")
N_("Raleigh-Durham")
N_("Randolph AFB")
N_("Rapid City")
N_("Rapid City-Ellsworth AFB")
N_("Ras Al Khaimah")
N_("Rawlins")
N_("Reading")
N_("Rebun Island")
N_("Recife")
N_("Red Bluff")
N_("Redding")
N_("Redig")
N_("Redmond")
N_("Red Oak")
N_("Redwood Falls")
N_("Reggio Calabria")
N_("Regina")
N_("Reims-Champagne")
N_("Rennes")
N_("Reno")
N_("Renton")
N_("Resistencia")
N_("Reus")
N_("Reyes")
N_("Reykjavik")
N_("Reynosa")
N_("Rhinelander")
N_("Rhode Island")
N_("Riberalta")
N_("Richmond")
N_("Rickenbacker")
N_("Rieti")
N_("Rifle")
N_("Riga")
N_("Rijeka")
N_("Rimini")
N_("Rio De Janeiro")
N_("Rio Gallegos")
N_("Rio Grande")
N_("Rioja")
N_("Rio / Jacarepagua")
N_("Rionegro/J.M.Cordova")
N_("Rishiri Island")
N_("Rivas")
N_("Rivera")
N_("Riverside")
N_("Riverside/March AFB")
N_("Riverton")
N_("Rivolto")
N_("Riyadh")
N_("Roanoke")
N_("Roatan")
N_("Robore")
N_("Rochester")
N_("Rockford")
N_("Rockland")
N_("Rockport")
N_("Rock Springs")
N_("Rocky Mount")
N_("Rodos")
N_("Rogers")
N_("Roma/Ciampino")
N_("Roma/Fiumicino")
N_("Romania")
N_("Roma/Urbe")
N_("Rome-Russell")
N_("Ronchi de' Legionari")
N_("Ronneby")
N_("Roosevelt")
N_("Roros")
N_("Rorvik/Ryum")
N_("Rosario")
N_("Roseburg")
N_("Roseglen")
N_("Rost")
N_("Rostov-Na-Donu")
N_("Roswell")
N_("Rotterdam")
N_("Rouen-Valle de Seine")
N_("Ruidoso-Sierra Blanca")
N_("Rurrenabaque")
N_("Russell")
N_("Russia")
N_("Rutland")
N_("Rygge")
N_("Rzeszow")
N_("Saarbrucken")
N_("Sabine Pass")
N_("Sacramento")
N_("Sacramento-Woodland")
N_("Safford-Municipal Airport")
N_("Saginaw")
N_("Saint Anthony")
N_("Saint-Brieuc-Armor")
N_("Saint-Dizier-Robinson")
N_("Saint-Etienne-Boutheon")
N_("Saint Mary's")
N_("Saint Mawgan")
N_("Saint-Nazaire-Montoir")
N_("Saint Paul")
N_("Saiq")
N_("Salalah")
N_("Salem")
N_("Salida")
N_("Salida-Harriet")
N_("Salina")
N_("Salinas")
N_("Salisbury")
N_("Salmon")
N_("Salmon (2)")
N_("Salta")
N_("Saltillo")
N_("Salt Lake City")
N_("Salto")
N_("Salt point")
N_("Salvador")
N_("Salzburg")
N_("Samara")
N_("Samos")
N_("Samsun")
N_("Sana'A")
N_("San Andres Isla/Sesquicentenario")
N_("San Angelo")
N_("San Antonio")
N_("San Antonio Del Tachira")
N_("San Antonio-Kelly AFB")
N_("San Antonio-Stinson")
N_("San Carlos")
N_("Sandane")
N_("Sandberg")
N_("Sanderson")
N_("San Diego")
N_("San Diego-Brown")
N_("San Diego-Miramar")
N_("San Diego-Montgomery")
N_("San Diego-North Island")
N_("San Diego-Santee")
N_("Sandnessjoen/Stokka")
N_("Sand Point")
N_("San Fernando De Apure")
N_("Sanford")
N_("San Francisco")
N_("Sangju")
N_("San Ignacio De Velasco")
N_("San Joaquin")
N_("San Jose")
N_("San Jose De Chiquitos")
N_("San Jose del Cabo")
N_("San Jose-Santa Clara")
N_("San Juan")
N_("Sankt-Peterburg")
N_("Sanliurfa")
N_("San Luis Obispo")
N_("San Luis Potosi")
N_("San Miguel")
N_("San Nicholas Island")
N_("San Salvador")
N_("San Sebastian")
N_("Santa Ana")
N_("Santa Barbara")
N_("Santa Cruz")
N_("Santa Fe")
N_("Santa Maria")
N_("Santa Marta/Simon Bolivar")
N_("Santa Monica")
N_("Santander")
N_("Santarem")
N_("Santa Rosa")
N_("Santa Rosa de Copan")
N_("Santiago")
N_("Santiago de Cuba")
N_("Santiago Del Estero")
N_("Santorini")
N_("Santos")
N_("Sao Jose Dos Campo")
N_("Sao Luiz")
N_("Sao Paulo")
N_("Sapporo Ab")
N_("Sarajevo")
N_("Saranac Lake")
N_("Sarasota")
N_("Saratov")
N_("Sarzana")
N_("Saskatchewan")
N_("Saskatoon")
N_("Sauce Viejo")
N_("Saudi Arabia")
N_("Sault Ste Marie")
N_("Savannah")
N_("Savannah-Hunter AAF")
N_("Sawyer AFB")
N_("Sayun")
N_("Scatsta")
N_("Schaffen")
N_("Schenectady")
N_("Scilly Isles")
N_("Scottsbluff")
N_("Scottsdale")
N_("Scranton")
N_("Seattle")
N_("Seattle-Boeing")
N_("Sedalia")
N_("Seeb")
N_("Selanik")
N_("Sendai Airport")
N_("Seoul E Ab")
N_("Seoul/Kimp'O International Airport")
N_("Seoul/Yongdungp'O Rokaf Wc")
N_("Sept-Iles")
N_("Seul Choix Pt")
N_("Sevilla")
N_("Seward")
N_("Sexton Summit")
N_("Shanghai")
N_("Shannon")
N_("Sharjah")
N_("Sharm El Sheikhintl")
N_("Sharurah")
N_("Shawbury")
N_("Shearwater")
N_("Sheboygan")
N_("Sheldon")
N_("Shelter Cove")
N_("Shelton")
N_("Shenandoah")
N_("Sheridan")
N_("Sherman-Denison")
N_("Shimofusa Ab")
N_("Shingle Point")
N_("Shiraz")
N_("Shishmaref")
N_("Shizuhama Ab")
N_("Shoreham")
N_("Show Low")
N_("Shreveport Downtown")
N_("Shreveport Regional")
N_("Sidney")
N_("Sigonella")
N_("Siloam Springs")
N_("Silver City")
N_("Sindal")
N_("Singapore")
N_("Sioux City")
N_("Sioux Falls")
N_("Sitka")
N_("Sivas")
N_("Sivrihisar")
N_("Skagway")
N_("Skiathos")
N_("Skien/Geiteryggen")
N_("Skive")
N_("Skopje")
N_("Skwentna")
N_("Slana")
N_("Slovakia")
N_("Slovenia")
N_("Smithers")
N_("Smyrna")
N_("Snowshoe Lake")
N_("Sochi")
N_("Socorro")
N_("Socotra")
N_("Soda Springs")
N_("Sofia")
N_("Sogndal")
N_("Soldotna")
N_("Somerset")
N_("Sonderborg")
N_("Songmu Ab")
N_("Sorkjosen")
N_("South Africa")
N_("Southampton")
N_("South Bend")
N_("South Carolina")
N_("South Dakota")
N_("Southend")
N_("South Marsh Island")
N_("South Timbalier")
N_("Spain")
N_("Sparrevohn")
N_("Spencer")
N_("Spickard")
N_("Split")
N_("Spokane")
N_("Spokane-Parkwater")
N_("Springbok")
N_("Springfield")
N_("Stampede Pass")
N_("State College")
N_("Stauning")
N_("Staunton")
N_("Stavanger/Sola")
N_("Staverton")
N_("Stavropol")
N_("St Cloud")
N_("Steamboat Springs")
N_("Stephenville")
N_("St. George")
N_("Stillwater")
N_("St. John's")
N_("St Johnsbury")
N_("St Joseph")
N_("St Louis")
N_("St Louis-Spirit")
N_("Stockholm (Arlanda)")
N_("Stockholm (Bromma)")
N_("Stockton")
N_("Stokmarknes/Skagen")
N_("Stord/Sorstokken")
N_("Storm Lake")
N_("Stornoway")
N_("St Paul")
N_("St Petersburg")
N_("St Petersburg / Clearwater")
N_("Strasbourg")
N_("Strevell")
N_("St Simon's Island")
N_("Stumpy Point")
N_("Sturgeon Bay")
N_("Stuttgart")
N_("Sucre")
N_("Sumburgh")
N_("Sumter")
N_("Sumter (2)")
N_("Sundsvall-Harnosand")
N_("Sungshan/Taipei")
N_("Superior")
N_("Suriname")
N_("Sutton")
N_("Suwon Ab")
N_("Svalbard")
N_("Svolvaer/Helle")
N_("Sweden")
N_("Swift Current")
N_("Switzerland")
N_("Sydney")
N_("Syktyvkar")
N_("Syracuse")
N_("Szczecin")
N_("Szombathely")
N_("Tabatinga")
N_("Tabriz")
N_("Tabuk")
N_("Tachikawa Ab")
N_("Tacna")
N_("Tacoma")
N_("Tacoma-Lakewood")
N_("Tacuarembo")
N_("Taegu")
N_("Taegu Ab")
N_("Taejon")
N_("Tahoe Valley")
N_("Taichung")
N_("Taif")
N_("Tainan")
N_("Taiwan")
N_("Taiyuan")
N_("Taiz")
N_("Tajima")
N_("Takamatsu Airport")
N_("Talara")
N_("Talinn")
N_("Talkeetna")
N_("Tallahassee")
N_("Tamanrasset")
N_("Tamanrasset/Aguenna")
N_("Tampa")
N_("Tampa-Macdill AFB")
N_("Tampere")
N_("Tampico")
N_("Tanana")
N_("Tanegashima Airport")
N_("Taos")
N_("Taoyuan")
N_("Tapachula")
N_("Taranto")
N_("Tarbes")
N_("Tarija")
N_("Tarvisio")
N_("Tatalina")
N_("Tateyama Ab")
N_("Taunton")
N_("Tebessa")
N_("Tees-Side")
N_("Tegucigalpa")
N_("Tehran-Mehrabad")
N_("Tela")
N_("Temple")
N_("Tennessee")
N_("Tepic")
N_("Teresina")
N_("Terre Haute")
N_("Terrell")
N_("Teterboro")
N_("Texarkana")
N_("Texas")
N_("The Dalles")
N_("Thessaloniki")
N_("Thief River Falls")
N_("Thiruvananthapuram")
N_("Thisted")
N_("Thompson Falls")
N_("Thumrait")
N_("Tianjin")
N_("Tijuana")
N_("Timisoara")
N_("Tin City")
N_("Tirana")
N_("Tiree")
N_("Tirgu Mures")
N_("Tiruchchirapalli")
N_("Titusville")
N_("Tivat")
N_("Tlemcen Zenata")
N_("Tobias Bolanos")
N_("Tocumen")
N_("Togiak Village")
N_("Tokachi GSDF")
N_("Tokunoshima Island")
N_("Tokushima Ab")
N_("Tokyo Heliport")
N_("Tokyo International Airport")
N_("Tokyo New International Airport")
N_("Toledo")
N_("Toluca")
N_("Tonopah")
N_("Topeka")
N_("Topeka-Forbes Field")
N_("Torino/Bric Della Croce")
N_("Torino/Caselle")
N_("Toronto")
N_("Torp")
N_("Torrance")
N_("Torreon")
N_("Tottori Airport")
N_("Toulouse")
N_("Toul-Rosieres")
N_("Tours-St-Symphorien")
N_("Toussus-Le Noble")
N_("Townsville")
N_("Toyama Airport")
N_("Trabzon")
N_("Trapani")
N_("Traverse City")
N_("Trelew")
N_("Trenton")
N_("Trevico")
N_("Treviso/Istrana")
N_("Treviso/S.Angelo")
N_("Trieste")
N_("Trinidad")
N_("Tripoli")
N_("Tromso/Langnes")
N_("Trondheim/Vaernes")
N_("Troutdale")
N_("Troyes/Barberey")
N_("Truckee")
N_("Truth or Consequences")
N_("Tsuiki Ab")
N_("Tsushima Airport")
N_("Tucson")
N_("Tucson-Davis AFB")
N_("Tucuman")
N_("Tucumcari")
N_("Tucurui")
N_("Tulancingo")
N_("Tulcea")
N_("Tulsa")
N_("Tupelo")
N_("Turaif")
N_("Turin")
N_("Turkey")
N_("Turku")
N_("Tuscaloosa")
N_("Tuxtla Gutierrez")
N_("Twenthe")
N_("Twentynine Palms")
N_("Twin Falls")
N_("Tyler")
N_("Tyndall AFB")
N_("Tyumen")
N_("Uberaba")
N_("Ufa")
N_("Ukiah")
N_("Ulan-Ude")
N_("Ulsan")
N_("Ulyanovsk")
N_("Umea")
N_("Umiat")
N_("Unalakleet")
N_("United Arab Emirates ")
N_("United Kingdom")
N_("United States")
N_("Unst")
N_("Upington")
N_("Uruapan")
N_("Uruguaiana")
N_("Uruguay")
N_("Urumqi")
N_("Utah")
N_("Utica")
N_("Utrecht/Soesterberg")
N_("Utsunomiya Ab")
N_("Vadso")
N_("Vaerlose")
N_("Vagar")
N_("Valdez 2")
N_("Valdosta")
N_("Valdosta-Moody AFB")
N_("Valencia")
N_("Valentine")
N_("Valera*")
N_("Valkenburg")
N_("Valley")
N_("Valparaiso")
N_("Valparaiso-Eglin AFB")
N_("Van")
N_("Vancouver")
N_("Vandel")
N_("Vandenberg AFB")
N_("Vandenberg Range")
N_("Van Nuys")
N_("Varadero")
N_("Varanasi/Babatpur")
N_("Varna")
N_("Vasteras")
N_("Vaxjo")
N_("Venezia")
N_("Venezuela")
N_("Venice")
N_("Veracruz")
N_("Vermillion")
N_("Vermont")
N_("Vernal")
N_("Vero Beach")
N_("Vicenza")
N_("Vichy-Charmeil")
N_("Vichy-Rolla")
N_("Vicksburg")
N_("Victoria")
N_("Viet Nam")
N_("Vigo")
N_("Vilhena")
N_("Villacoublay")
N_("Villafranca")
N_("Villahermosa")
N_("Villamontes")
N_("Villa Reynolds")
N_("Vilnius")
N_("Virginia")
N_("Virginia Beach")
N_("Virginia Tech Airport")
N_("Viru-Viru")
N_("Visalia")
N_("Visby")
N_("Viterbo")
N_("Vitoria")
N_("Vladikavkaz")
N_("Vladivostok")
N_("Vlieland")
N_("Vojens/Skrydstrup")
N_("Volgograd")
N_("Volkel")
N_("Volk Field")
N_("Voronezh")
N_("Voslau")
N_("Waco")
N_("Wadi Al Dawasser Airport")
N_("Wainwright")
N_("Wakefield")
N_("Wakkanai Airport")
N_("Walla Walla")
N_("Wallops Island")
N_("Walnut Ridge")
N_("Warner Robins")
N_("Warroad")
N_("Warszawa")
N_("Washington")
N_("Washington/Dulles")
N_("Waterbury")
N_("Waterloo")
N_("Watertown")
N_("Waterville")
N_("Waukesha")
N_("Wausau")
N_("Waycross")
N_("Waynesboro")
N_("Webster City")
N_("Wejh")
N_("Wellington")
N_("Wenatchee")
N_("Wendover")
N_("West Atlanta")
N_("West Burke")
N_("Westerland")
N_("Westfield")
N_("Westhampton")
N_("West Palm Beach")
N_("West Virginia")
N_("West Yellowstone")
N_("West Yellowstone (2)")
N_("Wheeling")
N_("Whidbey Island")
N_("Whitefield")
N_("White Plains")
N_("White Sulphur")
N_("Whittier")
N_("Wichita")
N_("Wichita Falls")
N_("Wichita-Jabara")
N_("Wichita-McConnell AFB")
N_("Wick")
N_("Wien")
N_("Wildwood")
N_("Wilkes - Barre")
N_("Williams Field")
N_("Williamsport")
N_("Williston")
N_("Willoughby")
N_("Willow Airport")
N_("Wilmington")
N_("Winchester")
N_("Windsor")
N_("Windsor Locks")
N_("Wink")
N_("Winnemucca")
N_("Winnipeg")
N_("Winslow")
N_("Winston-Salem")
N_("Winter Haven")
N_("Winter Park")
N_("Wiscasset")
N_("Wisconsin")
N_("Wisconsin Rapids")
N_("Wise")
N_("Woensdrecht")
N_("Wolf Point")
N_("Woong Cheon")
N_("Wooster")
N_("Worcester")
N_("Worland")
N_("Worthington")
N_("Wrangell")
N_("Wrightstown / Mcguire AFB")
N_("Wuchia Observatory")
N_("Wyoming")
N_("Xiamen")
N_("Yacuiba")
N_("Yakima")
N_("Yakushima")
N_("Yakutat")
N_("Yakutsk")
N_("Yamagata Airport")
N_("Yamaguchi Ube Airport")
N_("Yankton")
N_("Yao Airport")
N_("Yechon Ab")
N_("Yekaterinburg")
N_("Yellowknife")
N_("Yellowstone")
N_("Yemen")
N_("Yenbo")
N_("Yeoju Range")
N_("Yeonpyeungdo")
N_("Yeovilton")
N_("Yokosuka Fwf")
N_("Yokota Ab")
N_("Yongsan/H-208 Hp")
N_("Yoro")
N_("Yosu")
N_("Youngstown")
N_("Ypsilanti")
N_("Yugoslavia")
N_("Yukon")
N_("Yuma MCAS")
N_("Yurimaguas")
N_("Yuzhno-Sakhalinsk")
N_("Zacatecas")
N_("Zadar")
N_("Zagreb")
N_("Zakinthos")
N_("Zama Airfield")
N_("Zanesville")
N_("Zaragoza")
N_("Zell Am See")
N_("Zuni Pueblo")
N_("Zurich")
