/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window2");
gchar *s = N_("123");
gchar *s = N_("a");
gchar *s = N_("b");
gchar *s = N_("c");
gchar *s = N_("d");
gchar *s = N_("e");
gchar *s = N_("f");
gchar *s = N_("g");
gchar *s = N_("h");
gchar *s = N_("i");
gchar *s = N_("j");
gchar *s = N_("k");
gchar *s = N_("l");
gchar *s = N_("m");
gchar *s = N_("n");
gchar *s = N_("o");
gchar *s = N_("p");
gchar *s = N_("q");
gchar *s = N_("r");
gchar *s = N_("s");
gchar *s = N_("t");
gchar *s = N_("u");
gchar *s = N_("v");
gchar *s = N_("w");
gchar *s = N_("x");
gchar *s = N_("y");
gchar *s = N_("z");
