.TH "Evolution" "1" "1.2" "Ximian, Inc." "GNOME Applications"
.SH "NAME"
.LP 
evolution \- Run Ximian Evolution, a groupware suite for GNOME containing email, calendar, addressbook, and task\-list tools.
.SH "SYNOPSIS"
.LP 
evolution [OPTION] ... [URI]
.SH "DESCRIPTION"
.LP 
This program is a graphical groupware suite; a single application with email, calendar, address book, and task\-list tools to help you collaborate with other people.  

.LP 
This man page is not the central source of help for Evolution. You can find the user's guide by running the application and selecting items from the Help menu. Additional help and security information are available at the Ximian knowledge base online at \fBhttp://support.ximian.com\fR. For help with additional command\-line options, type evolution \-\-help at the command line.
.SH "EXAMPLES"
.TP 
\fBevolution\fR
Runs the application. 

.TP 
\fBevolution "%s"\fR
To use Evolution as the handler for \fImailto:\fR links in GNOME applications, open the GNOME Control Center and set the \fImailto:\fR URL handler to this value. You can do this with non\-GNOME browsers such as Mozilla, by setting the appropriate value in that application's preferences dialogs.

.TP 
\fBevolution mailto:joe@somewhere.net\fR
Open the message composer, addressing the message to \fIjoe@somewhere.net\fR.

.TP 	
\fBevolution evolution:/local/Inbox\fR
Start the application with the local Inbox folder open.

.TP 
\fBevolution default:mail\fR
Start the application with the folder mail/calendar/contacts/tasks open.

.TP 
\fBevolution \-\-no\-splash\fR
Start Evolution, but do not display the start\-up splash screen.

.TP 
\fBevolution \-\-debug\fR=\fIFILENAME\fR
Start the application, and output debugging messages to FILENAME.
