.\" 
.\" Evolution's compose command line utility manual page.
.\" (C) Ximian, Inc. http://www.ximian.com
.\"
.\" Author:
.\"   Miguel de Icaza (miguel@kernel.org)
.\"
.TH Evolution 1 "Evolution 1.0"
.SH NAME
compose \- invokes the Evolution Mail composer tool.
.SH SYNOPSIS
.PP
.B compose 
[\-\-subject SUBJECT] [\-s SUBJECT] [\-\-cc LIST] [\-c LIST] [\-\-bcc
LIST] [\-b LIST] [\-\-body FNAME] to...
.SH DESCRIPTION
The 
.I compose
program is a command line tool that can be used to invoke the
Evolution Mail composer directly from the command line, and allows for
simple configuration trough a number of flags.
.SH OPTIONS
The following options are supported
.TP
.I \-\-subject SUBJECT, \-s SUBJECT
Both forms are used to specify the subject to be used in the mail
message.
.TP
.I \-\-cc LIST, \-c LIST
Both forms are used to specify a comma separated list of addresses to
CC the message to.
.TP
.I \-\-bcc LIST, \-b LIST
Both forms are used to specify a comma separated list of addresses
that this message will be blind copied to.
.TP
.I \-\-body FNAME
Loads the filename FNAME as the contents for the Evolution Mail
composer. 
.SH OTHERS
If these options are not enough, you might want to look into accessing
the Evolution Mail Composer directly by using CORBA.
.SH INTERFACES
The Evolution Mail Composer supports the
IDL:GNOME/Evolution/Composer:1.0 interface and is implemented as the
component OAFIID:GNOME_Evolution_Mail_Composer.
.SH SEE ALSO
Evolution-Composer.idl
.SH BUGS
If you find bugs in the Evolution groupware suite, please report these
using the \fIbug-buddy\fP program in the GNOME distribution.