typedef union {
	float v_float;
	int   v_int;
	char* v_string;

  /* Renaming hack */
#define    yymaxdepth ical_yy_maxdepth
#define    yyparse ical_yy_parse
#define    yylex   ical_yy_lex
#define    yyerror ical_yy_error
#define    yylval  ical_yy_lval
#define    yychar  ical_yy_char
#define    yydebug ical_yy_debug
#define    yypact  ical_yy_pact
#define    yyr1    ical_yy_r1
#define    yyr2    ical_yy_r2
#define    yydef   ical_yy_def
#define    yychk   ical_yy_chk
#define    yypgo   ical_yy_pgo
#define    yyact   ical_yy_act
#define    yyexca  ical_yy_exca
#define yyerrflag ical_yy_errflag
#define yynerrs    ical_yy_nerrs
#define    yyps    ical_yy_ps
#define    yypv    ical_yy_pv
#define    yys     ical_yy_s
#define    yy_yys  ical_yy_yys
#define    yystate ical_yy_state
#define    yytmp   ical_yy_tmp
#define    yyv     ical_yy_v
#define    yy_yyv  ical_yy_yyv
#define    yyval   ical_yy_val
#define    yylloc  ical_yy_lloc
#define yyreds     ical_yy_reds
#define yytoks     ical_yy_toks
#define yylhs      ical_yy_yylhs
#define yylen      ical_yy_yylen
#define yydefred ical_yy_yydefred
#define yydgoto    ical_yy_yydgoto
#define yydefred ical_yy_yydefred
#define yydgoto    ical_yy_yydgoto
#define yysindex ical_yy_yysindex
#define yyrindex ical_yy_yyrindex
#define yygindex ical_yy_yygindex
#define yytable     ical_yy_yytable
#define yycheck     ical_yy_yycheck
#define yyname   ical_yy_yyname
#define yyrule   ical_yy_yyrule



} YYSTYPE;
#define	DIGITS	257
#define	INTNUMBER	258
#define	FLOATNUMBER	259
#define	STRING	260
#define	EOL	261
#define	EQUALS	262
#define	CHARACTER	263
#define	COLON	264
#define	COMMA	265
#define	SEMICOLON	266
#define	TIMESEPERATOR	267
#define	TRUE	268
#define	FALSE	269
#define	FREQ	270
#define	BYDAY	271
#define	BYHOUR	272
#define	BYMINUTE	273
#define	BYMONTH	274
#define	BYMONTHDAY	275
#define	BYSECOND	276
#define	BYSETPOS	277
#define	BYWEEKNO	278
#define	BYYEARDAY	279
#define	DAILY	280
#define	MINUTELY	281
#define	MONTHLY	282
#define	SECONDLY	283
#define	WEEKLY	284
#define	HOURLY	285
#define	YEARLY	286
#define	INTERVAL	287
#define	COUNT	288
#define	UNTIL	289
#define	WKST	290
#define	MO	291
#define	SA	292
#define	SU	293
#define	TU	294
#define	WE	295
#define	TH	296
#define	FR	297
#define	BIT8	298
#define	ACCEPTED	299
#define	ADD	300
#define	AUDIO	301
#define	BASE64	302
#define	BINARY	303
#define	BOOLEAN	304
#define	BUSY	305
#define	BUSYTENTATIVE	306
#define	BUSYUNAVAILABLE	307
#define	CALADDRESS	308
#define	CANCEL	309
#define	CANCELLED	310
#define	CHAIR	311
#define	CHILD	312
#define	COMPLETED	313
#define	CONFIDENTIAL	314
#define	CONFIRMED	315
#define	COUNTER	316
#define	DATE	317
#define	DATETIME	318
#define	DECLINECOUNTER	319
#define	DECLINED	320
#define	DELEGATED	321
#define	DISPLAY	322
#define	DRAFT	323
#define	DURATION	324
#define	EMAIL	325
#define	END	326
#define	FINAL	327
#define	FLOAT	328
#define	FREE	329
#define	GREGORIAN	330
#define	GROUP	331
#define	INDIVIDUAL	332
#define	INPROCESS	333
#define	INTEGER	334
#define	NEEDSACTION	335
#define	NONPARTICIPANT	336
#define	OPAQUE	337
#define	OPTPARTICIPANT	338
#define	PARENT	339
#define	PERIOD	340
#define	PRIVATE	341
#define	PROCEDURE	342
#define	PUBLIC	343
#define	PUBLISH	344
#define	RECUR	345
#define	REFRESH	346
#define	REPLY	347
#define	REQPARTICIPANT	348
#define	REQUEST	349
#define	RESOURCE	350
#define	ROOM	351
#define	SIBLING	352
#define	START	353
#define	TENTATIVE	354
#define	TEXT	355
#define	THISANDFUTURE	356
#define	THISANDPRIOR	357
#define	TIME	358
#define	TRANSPAENT	359
#define	UNKNOWN	360
#define	UTCOFFSET	361
#define	XNAME	362
#define	ALTREP	363
#define	CN	364
#define	CUTYPE	365
#define	DAYLIGHT	366
#define	DIR	367
#define	ENCODING	368
#define	EVENT	369
#define	FBTYPE	370
#define	FMTTYPE	371
#define	LANGUAGE	372
#define	MEMBER	373
#define	PARTSTAT	374
#define	RANGE	375
#define	RELATED	376
#define	RELTYPE	377
#define	ROLE	378
#define	RSVP	379
#define	SENTBY	380
#define	STANDARD	381
#define	URI	382
#define	TIME_CHAR	383
#define	UTC_CHAR	384


extern YYSTYPE yylval;
