/*-*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
 * CORBA interface for the Evolution shell.
 *
 * Authors:
 *   Iain Holmes  <iain@helixcode.com> 
 *
 * Copyright (C) 2000 Helix Code, Inc.
 */

#include <Bonobo.idl>

module Evolution {
	interface SummaryComponent;

	interface Summary: Bonobo::Unknown {
		exception NoSubWindow {};
		
		/**
		 * set_title:
		 * @component: The SummaryComponent whose window to set the title.
		 * @title: The title.
		 *
		 * Sets the title of the subwindow that displays @component
		 * to @title
		 */
		void set_title (in SummaryComponent component, 
				in string title)
			raises (NoSubWindow);

		/**
		 * flash:
		 * @component: The SummaryComponent that owns a subwindow.
		 *
		 * Flashes the subwindow that displays @component.
		 */
		 void flash (in SummaryComponent component)
			raises (NoSubWindow);

		/**
		 * update_html_component:
		 * @component: The SummaryComponent that owns a subwindow.
		 * @html: The new html that defines a component.
		 *
		 * Requests that the html that displays @component is changed
		 * to @html.
		 */
		void update_html_component (in SummaryComponent component,
					    in string html)
			raises (NoSubWindow);
	};
};
