/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("categories");
gchar *s = N_("Item(s) belong to these categories:");
gchar *s = N_("Available Categories:");
