/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Contact Editor");
gchar *s = N_("_Full Name...");
gchar *s = N_("File As:");
gchar *s = N_("Web page address:");
gchar *s = N_("Wants to receive _HTML mail");
gchar *s = N_("Address:");
gchar *s = N_("_Business");
gchar *s = N_("_Home");
gchar *s = N_("Business _Fax");
gchar *s = N_("_Mobile");
gchar *s = N_("Primary Email");
gchar *s = N_("B_usiness");
gchar *s = N_("_This is the mailing address");
gchar *s = N_("C_ontacts...");
gchar *s = N_("Ca_tegories...");
gchar *s = N_("_Job title:");
gchar *s = N_("_Company:");
gchar *s = N_("General");
gchar *s = N_("_Department:");
gchar *s = N_("_Office:");
gchar *s = N_("_Profession:");
gchar *s = N_("_Nickname:");
gchar *s = N_("_Spouse:");
gchar *s = N_("_Birthday:");
gchar *s = N_("_Assistant's name:");
gchar *s = N_("_Manager's Name:");
gchar *s = N_("Anni_versary:");
gchar *s = N_("No_tes:");
gchar *s = N_("Details");
gchar *s = N_("_Add");
gchar *s = N_("_Delete");
gchar *s = N_("Phone Types");
gchar *s = N_("New phone type");
gchar *s = N_("Add");
gchar *s = N_("New phone type");
