/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Contact Editor");
gchar *s = N_("_Full Name...");
gchar *s = N_("Company:");
gchar *s = N_("File As:");
gchar *s = N_("Web page address:");
gchar *s = N_("Wants _HTML mail");
gchar *s = N_("Address:");
gchar *s = N_("_Business");
gchar *s = N_("_Home");
gchar *s = N_("Business _Fax");
gchar *s = N_("_Mobile");
gchar *s = N_("Primary Email");
gchar *s = N_("Business");
gchar *s = N_("This is the _mailing address");
gchar *s = N_("_Contacts...");
gchar *s = N_("Ca_tegories...");
gchar *s = N_("Job Title");
gchar *s = N_("General");
gchar *s = N_("Department:");
gchar *s = N_("Office:");
gchar *s = N_("Profession:");
gchar *s = N_("Nickname:");
gchar *s = N_("Spouse:");
gchar *s = N_("Birthday:");
gchar *s = N_("Assistant's name:");
gchar *s = N_("Manager's Name:");
gchar *s = N_("Anniversary:");
gchar *s = N_("Notes:");
gchar *s = N_("Details");
gchar *s = N_("Add");
gchar *s = N_("Delete");
gchar *s = N_("Phone Types");
gchar *s = N_("New phone type");
gchar *s = N_("New phone type");
gchar *s = N_("Add");
