/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Check Full Name");
gchar *s = N_("\n"
              "Mr.\n"
              "Mrs.\n"
              "Dr.\n"
              "");
gchar *s = N_("\n"
              "Sr.\n"
              "Jr.\n"
              "I\n"
              "II\n"
              "III\n"
              "Esq.\n"
              "");
gchar *s = N_("_First:");
gchar *s = N_("_Title:");
gchar *s = N_("_Middle:");
gchar *s = N_("_Last:");
gchar *s = N_("_Suffix:");
