/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Check Address");
gchar *s = N_("_Street Address:");
gchar *s = N_("City:");
gchar *s = N_("State/Province:");
gchar *s = N_("Country:");
gchar *s = N_("ZIP/Postal Code:");
gchar *s = N_("E_xt:");
gchar *s = N_("USA\n"
              "Canada\n"
              "Finland\n"
              "");
gchar *s = N_("PO Box:");
