/*
 * Translatable strings file generated by extract-ui.
 * Add this file to your project's POTFILES.in
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Address _2:");
gchar *s = N_("Check Address");
gchar *s = N_("Countr_y:");
gchar *s = N_("_Address:");
gchar *s = N_("_City:");
gchar *s = N_("_PO Box:");
gchar *s = N_("_State/Province:");
gchar *s = N_("_ZIP Code:");
