.TH "Evolution" "1" "1.0" "Ximian, Inc." "GNOME Applications"
.SH "NAME"
.LP 
evolution \- Run Ximian Evolution, the GNOME groupware suite.
.SH "SYNOPSIS"
.LP 
evolution [OPTION] ... [URI]
.SH "DESCRIPTION"
.LP 
This program is a graphical groupware suite.  Documentation for
Evolution is available by running the application and selecting items
from the Help menu, or by visiting the Ximian knowledge base at
\fBhttp://support.ximian.com\fR.
.TP
\fB\-\-no-splash\fR
do not display the start-up splash screen
.TP
\fB\-\-debug\fR=\fIFILENAME\fR
output debugging messages to FILENAME
.SH "EXAMPLES"
To run this program the standard way type:
.sp
	\fBevolution\fR
.sp
To open the local Inbox folder
.sp
	\fBevolution evolution:/local/Inbox\fR
.sp
To open your default mail/calendar/contacts/tasks folder
.sp
	\fBevolution default:mail\fR
.sp
To send mail to \fBjoe@somewhere.net\fR
.sp
	\fBevolution mailto:joe@somewhere.net\fR
.sp
To use Evolution as the handler for \fBmailto:\fR links in GNOME
applications, set the GNOME URL handler in the GNOME Control Center to
be:
.sp
	\fBevolution "%s"\fR
.sp
(A similar approach works for Mozilla and other applications.)