/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Close");
gchar *s = N_("Snooze");
gchar *s = N_("Edit appointment");
gchar *s = N_("Snooze time (minutes)");
