/*
 * Translatable strings file generated by extract-ui.
 * Add this file to your project's POTFILES.in
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("12 hour (am/pm)");
gchar *s = N_("24 hour");
gchar *s = N_("Alarms timeout after");
gchar *s = N_("Audio Alarms");
gchar *s = N_("Beep when alarm windows appear.");
gchar *s = N_("Calendar");
gchar *s = N_("Calendar Preferences");
gchar *s = N_("Colors");
gchar *s = N_("Compress weekends");
gchar *s = N_("Date navigator options");
gchar *s = N_("Defaults");
gchar *s = N_("Display options");
gchar *s = N_("Due Date");
gchar *s = N_("Enable snoozing for");
gchar *s = N_("End of day:");
gchar *s = N_("First day of week:");
gchar *s = N_("Fri");
gchar *s = N_("Highlight");
gchar *s = N_("Items Due Today");
gchar *s = N_("Items Due Today:");
gchar *s = N_("Items Not Yet Due");
gchar *s = N_("Items Not Yet Due:");
gchar *s = N_("Mon");
gchar *s = N_("Overdue Items");
gchar *s = N_("Overdue Items:");
gchar *s = N_("Pick a color");
gchar *s = N_("Priority");
gchar *s = N_("Remind me of all appointments");
gchar *s = N_("Reminders");
gchar *s = N_("Sat");
gchar *s = N_("Show");
gchar *s = N_("Show appointment end times");
gchar *s = N_("Show week numbers");
gchar *s = N_("Start of day:");
gchar *s = N_("Sun");
gchar *s = N_("TaskPad");
gchar *s = N_("Thu");
gchar *s = N_("Time Until Due");
gchar *s = N_("Time divisions:");
gchar *s = N_("Time format:");
gchar *s = N_("Tue");
gchar *s = N_("Visual Alarms");
gchar *s = N_("Wed");
gchar *s = N_("Work week");
gchar *s = N_("minutes before they occur.");
gchar *s = N_("seconds.");
