/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Su_mmary:");
gchar *s = N_("Date & Time");
gchar *s = N_("Sta_rt Date:");
gchar *s = N_("_Due Date:");
gchar *s = N_("Progress");
gchar *s = N_("_Status:");
gchar *s = N_("Not Started\n"
              "In Progress\n"
              "Completed\n"
              "Cancelled\n"
              "");
gchar *s = N_("_Priority:");
gchar *s = N_("High\n"
              "Normal\n"
              "Low\n"
              "Undefined\n"
              "");
gchar *s = N_("% Comp_lete:");
gchar *s = N_("Classification");
gchar *s = N_("Pu_blic");
gchar *s = N_("Pri_vate");
gchar *s = N_("_Confidential");
gchar *s = N_("_Contacts...");
gchar *s = N_("Ca_tegories...");
gchar *s = N_("Task");
gchar *s = N_("Date Completed:");
gchar *s = N_("URL:");
gchar *s = N_("Details");
