# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4-p5 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /opt/evolution
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/evolution
pkglibdir = $(libdir)/evolution
pkgincludedir = $(includedir)/evolution

top_builddir = ..

ACLOCAL = aclocal -I macros
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = i386-netbsdelf1.5ZA
host_triplet = i386-pc-netbsdelf1.5ZA
AS = @AS@
BUILD_INCLUDED_LIBINTL = no
CAMEL_CFLAGS = -I/opt/evolution/include -I/usr/X11R6/include -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/pkg/include/gnome-xml -I/usr/X11R6/include/libglade-1.0 -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -D_REENTRANT    -I/usr/include
CAMEL_LIBS = -L/opt/evolution/lib -L/usr/X11R6/lib -Wl,-R/usr/X11R6/lib -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -lgal -lgnomeprint -lglade-gnome -lglade -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -lgdk_pixbuf -lgtk -lgdk -lgmodule -lglib -lintl -lXi -lXext -lX11 -lm -lgnomecanvaspixbuf -liconv -lxml -lz -lpthread -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -lgthread -lglib -lpthread     -lssl -lcrypto 
CAMEL_LOCK_HELPER_GROUP = 
CAMEL_LOCK_HELPER_USER = 
CATALOGS =  az.mo bg.mo ca.mo da.mo de.mo el.mo en_AU.mo en_GB.mo es.mo et.mo eu.mo fi.mo fr.mo ga.mo gl.mo hu.mo it.mo ja.mo ko.mo lt.mo lv.mo nl.mo nn.mo no.mo pl.mo pt.mo pt_BR.mo ro.mo ru.mo sk.mo sl.mo sv.mo tr.mo uk.mo zh_CN.mo zh_TW.mo
CATOBJEXT = .mo
CC = gcc
CPP = gcc -E
CXX = @CXX@
CXXCPP = @CXXCPP@
DATADIRNAME = lib
DB3_CFLAGS = -I/usr/local/db3/include
DB3_LDADD = /usr/local/db3/lib/libdb.a
DLLTOOL = @DLLTOOL@
EVOLUTION_ADDRESSBOOK_CFLAGS = -I/usr/local/include -I/usr/X11R6/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gnome-1.0 -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include1.1 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 -I/usr/X11R6/include/gconf/1 -DGTKHTML_HAVE_GCONF -I/usr/X11R6/include/gnome-vfs-1.0 -I/usr/X11R6/lib/gnome-vfs-1.0/include 
EVOLUTION_ADDRESSBOOK_CONDUIT_CFLAGS = -I/usr/local/include -I/usr/X11R6/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gnome-1.0 -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include1.1 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 -I/usr/X11R6/include/gconf/1 -DGTKHTML_HAVE_GCONF -I/usr/X11R6/include/gnome-vfs-1.0 -I/usr/X11R6/lib/gnome-vfs-1.0/include 
EVOLUTION_ADDRESSBOOK_CONDUIT_LIBS = -L/usr/local/lib -L/usr/X11R6/lib -L/usr/pkg/lib -L/home/pkgsrc/net/ORBit/work/.buildlink/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo_conf -lbonobo -lbonobox -lbonobo-print -lgtkhtml -lgal -lgnomeprint -lgdk_pixbuf -lgnomecanvaspixbuf -liconv -lgconf-gtk-1 -lgconf-1 -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm -lgnomevfs 
EVOLUTION_ADDRESSBOOK_LIBS = -L/usr/local/lib -L/usr/X11R6/lib -L/usr/pkg/lib -L/home/pkgsrc/net/ORBit/work/.buildlink/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo_conf -lbonobo -lbonobox -lbonobo-print -lgtkhtml -lgal -lgnomeprint -lgdk_pixbuf -lgnomecanvaspixbuf -liconv -lgconf-gtk-1 -lgconf-1 -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm -lgnomevfs 
EVOLUTION_CALENDAR_CFLAGS = -I/usr/local/include -I/usr/X11R6/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gnome-1.0 -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 -I/opt/evolution/include1.1 -I/usr/X11R6/include/gconf/1 -DGTKHTML_HAVE_GCONF -I/usr/X11R6/include/gnome-vfs-1.0 -I/usr/X11R6/lib/gnome-vfs-1.0/include 
EVOLUTION_CALENDAR_CONDUIT_CFLAGS = -I/usr/local/include -I/usr/X11R6/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gnome-1.0 -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 -I/opt/evolution/include1.1 -I/usr/X11R6/include/gconf/1 -DGTKHTML_HAVE_GCONF -I/usr/X11R6/include/gnome-vfs-1.0 -I/usr/X11R6/lib/gnome-vfs-1.0/include 
EVOLUTION_CALENDAR_CONDUIT_LIBS = -L/usr/local/lib -L/usr/X11R6/lib -L/usr/pkg/lib -L/home/pkgsrc/net/ORBit/work/.buildlink/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo_conf -lbonobo -lbonobox -lbonobo-print -lgtkhtml -lgal -lgnomeprint -lgdk_pixbuf -lgnomecanvaspixbuf -liconv -lgconf-gtk-1 -lgconf-1 -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm -lgnomevfs 
EVOLUTION_CALENDAR_LIBS = -L/usr/local/lib -L/usr/X11R6/lib -L/usr/pkg/lib -L/home/pkgsrc/net/ORBit/work/.buildlink/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo_conf -lbonobo -lbonobox -lbonobo-print -lgtkhtml -lgal -lgnomeprint -lgdk_pixbuf -lgnomecanvaspixbuf -liconv -lgconf-gtk-1 -lgconf-1 -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm -lgnomevfs 
EVOLUTION_DIR = /home/danw/gnome/evolution
EVOLUTION_EXECUTIVE_SUMMARY_CFLAGS = -I/usr/local/include -I/usr/X11R6/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gnome-1.0 -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 -I/opt/evolution/include1.1 -I/usr/X11R6/include/gconf/1 -DGTKHTML_HAVE_GCONF -I/usr/local/include/soup -I/usr/X11R6/include/gnome-vfs-1.0 -I/usr/X11R6/lib/gnome-vfs-1.0/include 
EVOLUTION_EXECUTIVE_SUMMARY_LIBS = -L/usr/local/lib -L/usr/X11R6/lib -L/usr/pkg/lib -L/home/pkgsrc/net/ORBit/work/.buildlink/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo_conf -lbonobo -lbonobox -lbonobo-print -lgtkhtml -lgal -lgnomeprint -lgdk_pixbuf -lgnomecanvaspixbuf -liconv -lgconf-gtk-1 -lgconf-1 -lglade-gnome -lglade -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lintl -lm -lsoup -lglib -lxml -lz -lgnomevfs 
EVOLUTION_MAIL_CFLAGS = -I/usr/local/include -I/usr/X11R6/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gnome-1.0 -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 -I/opt/evolution/include1.1 -I/usr/X11R6/include/gconf/1 -DGTKHTML_HAVE_GCONF -I/usr/X11R6/include/gnome-vfs-1.0 -I/usr/X11R6/lib/gnome-vfs-1.0/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -D_REENTRANT
EVOLUTION_MAIL_LIBS = -L/usr/local/lib -L/usr/X11R6/lib -L/usr/pkg/lib -L/home/pkgsrc/net/ORBit/work/.buildlink/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo_conf -lbonobo -lbonobox -lbonobo-print -lgtkhtml -lgal -lgnomeprint -lgdk_pixbuf -lgnomecanvaspixbuf -liconv -lgconf-gtk-1 -lgconf-1 -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm -lgnomevfs -lpthread -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -lgthread -lglib -lpthread
EXEEXT = 
E_NAME_CFLAGS = -I/usr/X11R6/include/gnome-1.0 -I/usr/X11R6/include -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 
E_NAME_LIBS = -L/usr/X11R6/lib -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo -lbonobox -lgal -lgnomeprint -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -lgdk_pixbuf -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnomecanvaspixbuf -liconv -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm 
E_UTIL_CFLAGS = -I/usr/X11R6/include/gnome-1.0 -I/usr/X11R6/include -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 
E_UTIL_LIBS = -L/usr/X11R6/lib -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo -lbonobox -lgal -lgnomeprint -lgdk_pixbuf -lgnomecanvaspixbuf -liconv -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -lm -lglib -lintl 
E_WIDGETS_CFLAGS = -I/usr/local/include -I/usr/X11R6/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gnome-1.0 -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/usr/X11R6/include/libglade-1.0 -I/usr/X11R6/include/gnome-vfs-1.0 -I/usr/X11R6/lib/gnome-vfs-1.0/include 
E_WIDGETS_LIBS = -L/usr/local/lib -L/usr/X11R6/lib -L/usr/pkg/lib -L/home/pkgsrc/net/ORBit/work/.buildlink/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -lbonobo_conf -lbonobo -lbonobox -lbonobo-print -lgnomeprint -lgdk_pixbuf -lgnomecanvaspixbuf -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm -lgnomevfs 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GENCAT = 
GMOFILES =  az.gmo bg.gmo ca.gmo da.gmo de.gmo el.gmo en_AU.gmo en_GB.gmo es.gmo et.gmo eu.gmo fi.gmo fr.gmo ga.gmo gl.gmo hu.gmo it.gmo ja.gmo ko.gmo lt.gmo lv.gmo nl.gmo nn.gmo no.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sv.gmo tr.gmo uk.gmo zh_CN.gmo zh_TW.gmo
GMSGFMT = /usr/bin/msgfmt
GNOMEGNORBA_LIBS = -lgnorba -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -lm -lglib -lintl
GNOMEUI_LIBS = -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -lm -lglib -lintl
GNOME_APPLETS_LIBS = 
GNOME_CAPPLET_LIBS = 
GNOME_CONFIG = /usr/X11R6/bin/gnome-config
GNOME_DOCKLETS_LIBS = 
GNOME_FULL_CFLAGS = -I/usr/local/include -I/usr/X11R6/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gnome-1.0 -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 -I/opt/evolution/include1.1 -I/usr/X11R6/include/gconf/1 -DGTKHTML_HAVE_GCONF -I/usr/X11R6/include/gnome-vfs-1.0 -I/usr/X11R6/lib/gnome-vfs-1.0/include 
GNOME_FULL_LIBS = -L/usr/local/lib -L/usr/X11R6/lib -L/usr/pkg/lib -L/home/pkgsrc/net/ORBit/work/.buildlink/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo_conf -lbonobo -lbonobox -lbonobo-print -lgtkhtml -lgal -lgnomeprint -lgdk_pixbuf -lgnomecanvaspixbuf -liconv -lgconf-gtk-1 -lgconf-1 -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm -lgnomevfs 
GNOME_INCLUDEDIR = -I/usr/X11R6/include -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gtk-1.2
GNOME_LIBDIR = -L/usr/X11R6/lib -Wl,-R/usr/X11R6/lib -L/usr/pkg/lib -Wl,-R/usr/pkg/lib
GNOME_LIBS = -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -lm -lglib -lintl
GNOME_PILOT_CFLAGS = 
GNOME_PILOT_LIBS = 
GNORBA_CFLAGS = -I/usr/X11R6/include -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gtk-1.2
GNORBA_LIBS = -L/usr/X11R6/lib -Wl,-R/usr/X11R6/lib -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -lgnorba -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -lm -lglib -lintl
GTKDOC = false
GTKHTML_DATADIR = /opt/evolution/share
GTKXMHTML_LIBS = -lgtkxmhtml -lXpm -ljpeg -lpng -lz -lSM -lICE -lgtk -lgdk -lgmodule -lglib -lintl -lXi -lXext -lX11 -lm
GTK_CFLAGS = -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/X11R6/include
GTK_CONFIG = /usr/X11R6/bin/gtk-config
GTK_LIBS = -lSM -lICE -L/usr/X11R6/lib -Wl,-R/usr/X11R6/lib -Wl,-R/usr/X11R6/lib -L/usr/X11R6/lib -L/usr/X11R6/lib -lgtk -lgdk -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -lgmodule -lglib -L/usr/pkg/lib -lintl -lXi -lXext -lX11 -lm
GT_NO = 
GT_YES = #YES#
HAVE_JW = no
HTML_DIR = ${datadir}/gnome/html
IMPORTERS_CFLAGS = -I/usr/local/include -I/usr/X11R6/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gnome-1.0 -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/usr/X11R6/include/libglade-1.0 -I/usr/X11R6/include/gnome-vfs-1.0 -I/usr/X11R6/lib/gnome-vfs-1.0/include 
IMPORTERS_LIBS = -L/usr/local/lib -L/usr/X11R6/lib -L/usr/pkg/lib -L/home/pkgsrc/net/ORBit/work/.buildlink/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -lbonobo_conf -lbonobo -lbonobox -lbonobo-print -lgnomeprint -lgdk_pixbuf -lgnomecanvaspixbuf -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm -lgnomevfs 
INCLUDE_LOCALE_H = #include <locale.h>
INSTOBJEXT = .mo
INTLDEPS = 
INTLLIBS = -lintl
INTLOBJS = 
JW = no
KDE_APPLNK_DIR = 
KRB4_CFLAGS = 
KRB4_LDFLAGS = 
KRB5_CFLAGS = 
KRB5_LDFLAGS = 
LDAP_CFLAGS = 
LDAP_LIBS = 
LEX = flex
LIBFILTER_CFLAGS = -I/usr/X11R6/include/gnome-1.0 -I/usr/X11R6/include -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 
LIBFILTER_LIBS = -L/usr/X11R6/lib -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lgal -lgnomeprint -liconv -lgdk_pixbuf -lgnomecanvaspixbuf -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -lm -lglib -lintl 
LIBIBEX_CFLAGS = -I/usr/local/include -I/usr/X11R6/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gnome-1.0 -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 -I/usr/X11R6/include/gnome-vfs-1.0 -I/usr/X11R6/lib/gnome-vfs-1.0/include 
LIBIBEX_LIBS = -L/usr/local/lib -L/usr/X11R6/lib -L/usr/pkg/lib -L/home/pkgsrc/net/ORBit/work/.buildlink/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo_conf -lbonobo -lbonobox -lbonobo-print -lgal -lgnomeprint -liconv -lgdk_pixbuf -lgnomecanvaspixbuf -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm -lgnomevfs 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAINT = #
MAKEINFO = makeinfo
MKINSTALLDIRS = ./mkinstalldirs
NSPR_CFLAGS = 
NSPR_LDFLAGS = 
NSS_CFLAGS = 
NSS_LDFLAGS = 
OBJDUMP = @OBJDUMP@
OBJEXT = o
OPENSSL_CFLAGS = -I/usr/include
OPENSSL_LDFLAGS =  -lssl -lcrypto 
ORBIT_CFLAGS = -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include/orbit-1.0
ORBIT_CONFIG = /usr/pkg/bin/orbit-config
ORBIT_IDL = /usr/pkg/bin/orbit-idl
ORBIT_LIBS = -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm
PACKAGE = evolution
PISOCK_CFLAGS = 
PISOCK_LIBS = 
POFILES =  az.po bg.po ca.po da.po de.po el.po en_AU.po en_GB.po es.po et.po eu.po fi.po fr.po ga.po gl.po hu.po it.po ja.po ko.po lt.po lv.po nl.po nn.po no.po pl.po pt.po pt_BR.po ro.po ru.po sk.po sl.po sv.po tr.po uk.po zh_CN.po zh_TW.po
POSUB = po
PTHREAD_LIB = -lpthread
PURIFY = impure 
RANLIB = ranlib
SCROLLKEEPER_CONFIG = /usr/pkg/bin/scrollkeeper-config
SCROLLKEEPER_LOCALSTATE_DIR = /usr/pkg/var/lib/scrollkeeper
SCROLLKEEPER_REQUIRED = 0.1.4
SENDMAIL = /usr/sbin/sendmail
SHELL_CFLAGS = -I/usr/local/include -I/usr/X11R6/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gnome-1.0 -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 -I/opt/evolution/include1.1 -I/usr/X11R6/include/gconf/1 -DGTKHTML_HAVE_GCONF -I/usr/X11R6/include/gnome-vfs-1.0 -I/usr/X11R6/lib/gnome-vfs-1.0/include 
SHELL_LIBS = -L/usr/local/lib -L/usr/X11R6/lib -L/usr/pkg/lib -L/home/pkgsrc/net/ORBit/work/.buildlink/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo_conf -lbonobo -lbonobox -lbonobo-print -lgtkhtml -lgal -lgnomeprint -lgdk_pixbuf -lgnomecanvaspixbuf -liconv -lgconf-gtk-1 -lgconf-1 -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm -lgnomevfs 
STRIP = strip
THREADS_CFLAGS = -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -D_REENTRANT
THREADS_LIBS = -lpthread -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -lgthread -lglib -lpthread
USE_INCLUDED_LIBINTL = no
USE_NLS = yes
VERSION = 1.1.0.99
WOMBAT_CFLAGS = -I/usr/local/include -I/usr/X11R6/include -I/usr/pkg/include/glib/glib-1.2 -I/usr/pkg/lib/glib/include -I/usr/pkg/include -I/usr/X11R6/include/gnome-1.0 -DNEED_GNOMESUPPORT_H -I/usr/X11R6/lib/gnome-libs/include -I/usr/X11R6/include/gtk-1.2 -I/usr/pkg/include/gnome-xml -I/usr/pkg/include/orbit-1.0 -I/opt/evolution/include -I/usr/X11R6/include/libglade-1.0 -I/opt/evolution/include1.1 -I/usr/X11R6/include/gconf/1 -DGTKHTML_HAVE_GCONF -I/usr/X11R6/include/gnome-vfs-1.0 -I/usr/X11R6/lib/gnome-vfs-1.0/include 
WOMBAT_LIBS = -L/usr/local/lib -L/usr/X11R6/lib -L/usr/pkg/lib -L/home/pkgsrc/net/ORBit/work/.buildlink/lib -Wl,-R/usr/pkg/lib -Wl,-R/usr/X11R6/lib -L/opt/evolution/lib -lbonobo_conf -lbonobo -lbonobox -lbonobo-print -lgtkhtml -lgal -lgnomeprint -lgdk_pixbuf -lgnomecanvaspixbuf -liconv -lgconf-gtk-1 -lgconf-1 -lglade-gnome -lglade -lxml -lz -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXi -lXext -lX11 -lgnome -lgnomesupport -lesd -lossaudio -laudiofile -loaf -lORBitCosNaming -lORBit -lIIOP -lwrap -lORBitutil -lglib -lintl -lm -lgnomevfs 
XML_I18N_EXTRACT = $(top_builddir)/xml-i18n-extract
XML_I18N_MERGE = $(top_builddir)/xml-i18n-merge
XML_I18N_TOOLS_PERL = /usr/pkg/bin/perl
XML_I18N_UPDATE = $(top_builddir)/xml-i18n-update
XPM_LIBS = -lXpm
YACC = bison -y
ZVT_LIBS = -lzvt -lutil -lSM -lICE -lgdk_imlib -lgtk -lgdk -lgmodule -lglib -lXi -lXext -lX11 -lm -lintl
camel_providerdir = $(libdir)/evolution/camel-providers/1.1
cflags_set = yes
cxxflags_set = @cxxflags_set@
l = 
localedir = $(prefix)/$(DATADIRNAME)/locale

MACROS =    aclocal-include.m4				  compiler-flags.m4				  curses.m4					  gnome-bonobo-check.m4				  gnome-fileutils.m4				  gnome-ghttp-check.m4				  gnome-gnorba-check.m4				  gnome-guile-checks.m4				  gnome-libgtop-check.m4			  gnome-objc-checks.m4				  gnome-orbit-check.m4				  gnome-print-check.m4				  gnome-pthread-check.m4			  gnome-support.m4				  gnome-undelfs.m4				  gnome-vfs.m4					  gnome-x-checks.m4				  gnome-xml-check.m4				  gnome.m4					  gperf-check.m4				  linger.m4					  need-declaration.m4				


EXTRA_DIST = $(MACROS) gnome-common.m4 gnome-gettext.m4 autogen.sh
MAINTAINERCLEANFILES = macros.dep

#gnome_aclocaldir = $(datadir)/aclocal/gnome-macros

#gnome_aclocal_DATA = $(MACROS) gnome-macros.dep gnome-common.m4 	gnome-gettext.m4 autogen.sh
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
DATA =  $(gnome_aclocal_DATA)

DIST_COMMON =  ChangeLog Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu macros/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


install-gnome_aclocalDATA: $(gnome_aclocal_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(gnome_aclocaldir)
	@list='$(gnome_aclocal_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(gnome_aclocaldir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(gnome_aclocaldir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(gnome_aclocaldir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(gnome_aclocaldir)/$$p; \
	  fi; fi; \
	done

uninstall-gnome_aclocalDATA:
	@$(NORMAL_UNINSTALL)
	list='$(gnome_aclocal_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(gnome_aclocaldir)/$$p; \
	done
tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = macros

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu macros/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-gnome_aclocalDATA
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-gnome_aclocalDATA
uninstall: uninstall-am
all-am: Makefile $(DATA)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(gnome_aclocaldir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: uninstall-gnome_aclocalDATA install-gnome_aclocalDATA tags \
distdir info-am info dvi-am dvi check check-am installcheck-am \
installcheck install-exec-am install-exec install-data-am install-data \
install-am install uninstall-am uninstall all-redirect all-am all \
installdirs mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


#macros.dep: Makefile.am
#	@echo '$$(top_srcdir)/aclocal.m4: $(MACROS:%=macros/%)' > $@

#gnome-macros.dep: Makefile.am
#	@echo '$$(top_srcdir)/aclocal.m4: $(MACROS:%=$(gnome_aclocaldir)/%)' > $@

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
