/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Select Names");
gchar *s = N_("Find...");
gchar *s = N_("Select name from List:");
gchar *s = N_("Message Recipients");
