#define DBIND_ALIGNOF_CHAR          1
#define DBIND_ALIGNOF_DBIND_POINTER 4
#define DBIND_ALIGNOF_DBIND_STRUCT  1
#define DBIND_ALIGNOF_DBUS_BOOL_T   4
#define DBIND_ALIGNOF_DBUS_INT16_T  2
#define DBIND_ALIGNOF_DBUS_INT32_T  4
#define DBIND_ALIGNOF_DBUS_INT64_T  4
#define DBIND_ALIGNOF_DOUBLE        4
