/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Mail Configuration");
gchar *s = N_("Mail Configuration");
gchar *s = N_("Welcome to the Evolution Mail configuration wizard!\n"
              "By filling in some information about your email\n"
              "settings, you can start sending and receiving email\n"
              "right away. Click Next to continue.");
gchar *s = N_("Identity");
gchar *s = N_("Mail Source");
gchar *s = N_("Mail Transport");
gchar *s = N_("Mail Configuration");
gchar *s = N_("Your email configuration is now complete.\n"
              "Click \"Finish\" to save your new settings");
