/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Identities");
gchar *s = N_("Address");
gchar *s = N_("Organization");
gchar *s = N_("Signature File");
gchar *s = N_("Add");
gchar *s = N_("Edit");
gchar *s = N_("Delete");
gchar *s = N_("Identities");
gchar *s = N_("Sources");
gchar *s = N_("Add");
gchar *s = N_("Edit");
gchar *s = N_("Delete");
gchar *s = N_("Mail Sources");
gchar *s = N_("Transport");
gchar *s = N_("News Servers");
gchar *s = N_("Add");
gchar *s = N_("Edit");
gchar *s = N_("Delete");
gchar *s = N_("News Sources");
gchar *s = N_("Send messages in HTML format");
gchar *s = N_("Other");
