/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Mail Configuration Druid");
gchar *s = N_("Mail Configuration");
gchar *s = N_("Welcome to the Evolution Mail Configuration Druid.\n"
              "\n"
              "Click \"Next\" to begin. ");
gchar *s = N_("Identity");
gchar *s = N_("Required");
gchar *s = N_("Email Address:");
gchar *s = N_("Full Name:");
gchar *s = N_("Optional");
gchar *s = N_("Organization:");
gchar *s = N_("Signature file:");
gchar *s = N_("Receiving Email");
gchar *s = N_("Server Type: ");
gchar *s = N_("Server Configuration");
gchar *s = N_("Host:");
gchar *s = N_("Username:");
gchar *s = N_("Path:");
gchar *s = N_("Keep mail on server");
gchar *s = N_("Authentication");
gchar *s = N_("Authentication");
gchar *s = N_("Authentication Type:");
gchar *s = N_("Password:");
gchar *s = N_("Remember my password");
gchar *s = N_("Sending Email");
gchar *s = N_("Server Type: ");
gchar *s = N_("Server Configuration");
gchar *s = N_("Host:");
gchar *s = N_("Server requires authentication");
gchar *s = N_("Account Management");
gchar *s = N_("Account Information");
gchar *s = N_("Name:");
gchar *s = N_("Make this my default account");
gchar *s = N_("Done");
gchar *s = N_("Congratulations, your mail configuration is complete.\n"
              "\n"
              "You are now ready to send and receive email \n"
              "using Evolution. \n"
              "\n"
              "Click \"Finish\" to save your settings.");
gchar *s = N_("Evolution Mail Configuration");
gchar *s = N_("Account");
gchar *s = N_("Type");
gchar *s = N_("Add");
gchar *s = N_("Edit");
gchar *s = N_("Delete");
gchar *s = N_("Default");
gchar *s = N_("Mail");
gchar *s = N_("Sources");
gchar *s = N_("Add");
gchar *s = N_("Edit");
gchar *s = N_("Delete");
gchar *s = N_("News");
gchar *s = N_("Edit Mail Configuration Settings");
gchar *s = N_("Identity");
gchar *s = N_("Full Name:");
gchar *s = N_("Email Address:");
gchar *s = N_("Add Optional Fields...");
gchar *s = N_("Receiving Mail");
gchar *s = N_("IMAP");
gchar *s = N_("Type:");
gchar *s = N_("Server:");
gchar *s = N_("Username:");
gchar *s = N_("Path:");
gchar *s = N_("Authentication:");
gchar *s = N_("Password:");
gchar *s = N_("Kerberos \n"
              "Plain-text Password\n"
              "");
gchar *s = N_("Don't delete messages from server");
gchar *s = N_("Sending Mail");
gchar *s = N_("Server:");
gchar *s = N_("Type:");
gchar *s = N_("SMTP");
gchar *s = N_("Authentication:");
gchar *s = N_("Kerberos \n"
              "Plain-text Password\n"
              "");
gchar *s = N_("Additional Identity Fields");
gchar *s = N_("Optional Information");
gchar *s = N_("Organization:");
gchar *s = N_("Signature file:");
gchar *s = N_("Select your signature file");
gchar *s = N_("Reply-to:");
