/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Display folders whose name contain:");
gchar *s = N_("All Folders");
gchar *s = N_("Subscribed");
gchar *s = N_("Query");
gchar *s = N_("Subscribe");
gchar *s = N_("Unsubscribe");
