/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Field Chooser");
gchar *s = N_("To add a column to your table, drag it into\n"
              "the location in which you want it to appear.");
