/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Fields");
gchar *s = N_("Grouping");
gchar *s = N_("Sort");
gchar *s = N_("Filter");
