/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("Calendar Message");
gchar *s = N_("Date:");
gchar *s = N_("Organizer:");
gchar *s = N_("Summary:");
gchar *s = N_("Description:");
gchar *s = N_("date-start");
gchar *s = N_("--to--");
gchar *s = N_("date-end");
gchar *s = N_("Sender");
gchar *s = N_("Loading Calendar");
gchar *s = N_("Loading calendar...");
gchar *s = N_("%P %%");
