/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Meeting Invitations");
gchar *s = N_("Publish\n"
              "Event");
gchar *s = N_("Request\n"
              "Meeting");
gchar *s = N_("Cancel\n"
              "Meeting");
gchar *s = N_("Schedule\n"
              "Time");
gchar *s = N_("Organizer: ");
gchar *s = N_("Attendees: ");
gchar *s = N_("Add");
gchar *s = N_("Delete");
gchar *s = N_("Edit");
gchar *s = N_("Attendee");
gchar *s = N_("Role");
gchar *s = N_("RSVP");
gchar *s = N_("Status");
gchar *s = N_("Attendee");
gchar *s = N_("Attendee address");
gchar *s = N_("Role");
gchar *s = N_("Chair\n"
              "Required Participant\n"
              "Optional Participant\n"
              "Non-Participant\n"
              "Other\n"
              "\n"
              "\n"
              "");
gchar *s = N_("Required Participant");
gchar *s = N_("RSVP");
