/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("event-editor-dialog");
gchar *s = N_("Su_mmary:");
gchar *s = N_("Time");
gchar *s = N_("_Start time:");
gchar *s = N_("_End time:");
gchar *s = N_("A_ll day event");
gchar *s = N_("Classification");
gchar *s = N_("Pu_blic");
gchar *s = N_("Pri_vate");
gchar *s = N_("_Confidential");
gchar *s = N_("_Contacts");
gchar *s = N_("Ca_tegories...");
gchar *s = N_("General");
gchar *s = N_("Minutes\n"
              "Hours\n"
              "Days\n"
              "");
gchar *s = N_("Minutes\n"
              "Hours\n"
              "Days\n"
              "");
gchar *s = N_("Minutes\n"
              "Hours\n"
              "Days\n"
              "");
gchar *s = N_("Minutes\n"
              "Hours\n"
              "Days\n"
              "");
gchar *s = N_("_Display");
gchar *s = N_("_Program");
gchar *s = N_("_Mail");
gchar *s = N_("Mail _to:");
gchar *s = N_("_Run program:");
gchar *s = N_("_Audio");
gchar *s = N_("Reminder");
gchar *s = N_("Appointment Basics");
gchar *s = N_("Su_mmary:");
gchar *s = N_("_Starting date:");
gchar *s = N_("Recurrence Rule");
gchar *s = N_("No recurrence");
gchar *s = N_("Simple recurrence");
gchar *s = N_("Custom recurrence");
gchar *s = N_("Every");
gchar *s = N_("day(s)\n"
              "week(s)\n"
              "month(s)\n"
              "year(s)\n"
              "");
gchar *s = N_("for\n"
              "until\n"
              "forever\n"
              "");
gchar *s = N_("Exceptions");
gchar *s = N_("Add");
gchar *s = N_("Modify");
gchar *s = N_("Delete");
gchar *s = N_("label21");
gchar *s = N_("Preview");
gchar *s = N_("Recurrence");
