/*
 * Translatable strings file generated by extract-ui.
 * Add this file to your project's POTFILES.in
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("A_ll day event");
gchar *s = N_("Add");
gchar *s = N_("Appointment Basics");
gchar *s = N_("Classification");
gchar *s = N_("Custom recurrence");
gchar *s = N_("Delete");
gchar *s = N_("Every");
gchar *s = N_("Exceptions");
gchar *s = N_("General");
gchar *s = N_("Mail _to:");
gchar *s = N_("Modify");
gchar *s = N_("No recurrence");
gchar *s = N_("Pri_vate");
gchar *s = N_("Pu_blic");
gchar *s = N_("Recur on the");
gchar *s = N_("Recurrence");
gchar *s = N_("Recurrence Rule");
gchar *s = N_("Reminder");
gchar *s = N_("Simple recurrence");
gchar *s = N_("Su_mmary:");
gchar *s = N_("This appointment has custom recurrence rules that cannot be edited by Evolution.");
              "");
              "However, the appointment will recur at the appropriate time and will be displayed properly in the calendar views.");
gchar *s = N_("Time");
gchar *s = N_("_Audio");
gchar *s = N_("_Confidential");
gchar *s = N_("_Display");
gchar *s = N_("_End time:");
gchar *s = N_("_Mail");
gchar *s = N_("_Program");
gchar *s = N_("_Run program:");
<<<<<<< event-editor-dialog.glade.h
gchar *s = N_("_Start time:");
=======
gchar *s = N_("_Audio");
gchar *s = N_("Reminder");
gchar *s = N_("Appointment Basics");
gchar *s = N_("Su_mmary:");
>>>>>>> 1.9
gchar *s = N_("_Starting date:");
gchar *s = N_("event-editor-dialog");
gchar *s = N_("label21");
gchar *s = N_("month(s)");
<<<<<<< event-editor-dialog.glade.h
gchar *s = N_("th day of the month");
=======
gchar *s = N_("year(s)");
gchar *s = N_("for");
gchar *s = N_("until");
gchar *s = N_("forever");
gchar *s = N_("Exceptions");
gchar *s = N_("Add");
gchar *s = N_("Modify");
gchar *s = N_("Delete");
gchar *s = N_("label21");
gchar *s = N_("Preview");
gchar *s = N_("Recurrence");
>>>>>>> 1.11
