/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("_Owner:");
gchar *s = N_("_Summary:");
gchar *s = N_("Time");
gchar *s = N_("Start time:");
gchar *s = N_("End time:");
gchar *s = N_("A_ll day event");
gchar *s = N_("Alarms");
gchar *s = N_("Minutes\n"
              "Hours\n"
              "Days\n"
              "");
gchar *s = N_("Minutes\n"
              "Hours\n"
              "Days\n"
              "");
gchar *s = N_("Minutes\n"
              "Hours\n"
              "Days\n"
              "");
gchar *s = N_("Minutes\n"
              "Hours\n"
              "Days\n"
              "");
gchar *s = N_("_Display");
gchar *s = N_("_Audio");
gchar *s = N_("_Program");
gchar *s = N_("_Mail");
gchar *s = N_("Mail _to");
gchar *s = N_("_Run program");
gchar *s = N_("Classification");
gchar *s = N_("Pu_blic");
gchar *s = N_("Pri_vate");
gchar *s = N_("_Confidential");
gchar *s = N_("General");
gchar *s = N_("Recurrence rule");
gchar *s = N_("None");
gchar *s = N_("Daily");
gchar *s = N_("Weekly");
gchar *s = N_("Monthly");
gchar *s = N_("Yearly");
gchar *s = N_("label23");
gchar *s = N_("Every ");
gchar *s = N_("day(s)");
gchar *s = N_("label24");
gchar *s = N_("Every ");
gchar *s = N_("week(s)");
gchar *s = N_("Mon");
gchar *s = N_("Tue");
gchar *s = N_("Wed");
gchar *s = N_("Thu");
gchar *s = N_("Fri");
gchar *s = N_("Sat");
gchar *s = N_("Sun");
gchar *s = N_("label25");
gchar *s = N_("Recur on the");
gchar *s = N_("th day of the month");
gchar *s = N_("Recur on the");
gchar *s = N_("1st\n"
              "2nd\n"
              "3rd\n"
              "4th\n"
              "5th\n"
              "");
gchar *s = N_("Monday\n"
              "Tuesday\n"
              "Wednesday\n"
              "Thursday\n"
              "Friday\n"
              "Saturday\n"
              "Sunday\n"
              "");
gchar *s = N_("Every");
gchar *s = N_("month(s)");
gchar *s = N_("label26");
gchar *s = N_("Every ");
gchar *s = N_("year(s)");
gchar *s = N_("label27");
gchar *s = N_("Ending date");
gchar *s = N_("Repeat forever");
gchar *s = N_("End on ");
gchar *s = N_("End after");
gchar *s = N_("occurrence(s)");
gchar *s = N_("Exceptions");
gchar *s = N_("Add");
gchar *s = N_("Change");
gchar *s = N_("Delete");
gchar *s = N_("Recurrence");
