/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "Evolution-Composer.h"

#if ( (TC_IMPL_TC_Evolution_Composer_0 == 'E') \
&& (TC_IMPL_TC_Evolution_Composer_1 == 'v') \
&& (TC_IMPL_TC_Evolution_Composer_2 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_3 == 'l') \
&& (TC_IMPL_TC_Evolution_Composer_4 == 'u') \
&& (TC_IMPL_TC_Evolution_Composer_5 == 't') \
&& (TC_IMPL_TC_Evolution_Composer_6 == 'i') \
&& (TC_IMPL_TC_Evolution_Composer_7 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_8 == 'n') \
&& (TC_IMPL_TC_Evolution_Composer_9 == '_') \
&& (TC_IMPL_TC_Evolution_Composer_10 == 'C') \
&& (TC_IMPL_TC_Evolution_Composer_11 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_12 == 'm') \
&& (TC_IMPL_TC_Evolution_Composer_13 == 'p') \
&& (TC_IMPL_TC_Evolution_Composer_14 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_15 == 's') \
&& (TC_IMPL_TC_Evolution_Composer_16 == 'e') \
&& (TC_IMPL_TC_Evolution_Composer_17 == 'r') \
) && !defined(TC_DEF_TC_Evolution_Composer)
#define TC_DEF_TC_Evolution_Composer 1
const struct CORBA_TypeCode_struct TC_Evolution_Composer_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Composer", "IDL:Evolution/Composer:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Evolution_Composer_Recipient_0 == 'E') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_1 == 'v') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_2 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_3 == 'l') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_4 == 'u') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_5 == 't') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_6 == 'i') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_7 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_8 == 'n') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_9 == '_') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_10 == 'C') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_11 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_12 == 'm') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_13 == 'p') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_14 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_15 == 's') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_16 == 'e') \
&& (TC_IMPL_TC_Evolution_Composer_Recipient_17 == 'r') \
) && !defined(TC_DEF_TC_Evolution_Composer_Recipient)
#define TC_DEF_TC_Evolution_Composer_Recipient 1
static const char *anon_subnames_array5[] = { "name", "address" };
static const CORBA_TypeCode anon_subtypes_array6[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
      (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_Evolution_Composer_Recipient_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_struct, "Recipient", "IDL:Evolution/Composer/Recipient:1.0",
   0, 2,
   (const char **) anon_subnames_array5,
   (CORBA_TypeCode *) anon_subtypes_array6,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_0 == 'E') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_3 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_4 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_6 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_7 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_10 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_11 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_12 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_13 == 'p') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_14 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_15 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_16 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_17 == 'r') \
) && !defined(TC_DEF_TC_CORBA_sequence_Evolution_Composer_Recipient)
#define TC_DEF_TC_CORBA_sequence_Evolution_Composer_Recipient 1
static const CORBA_TypeCode anon_subtypes_array10[] =
   { (CORBA_TypeCode) & TC_Evolution_Composer_Recipient_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_Evolution_Composer_Recipient_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array10,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_0 == 'E') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_1 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_3 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_4 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_5 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_6 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_7 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_10 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_11 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_12 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_13 == 'p') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_14 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_15 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_16 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Evolution_Composer_Recipient_17 == 'r') \
) && !defined(TC_DEF_TC_CORBA_sequence_Evolution_Composer_Recipient)
#define TC_DEF_TC_CORBA_sequence_Evolution_Composer_Recipient 1
static const CORBA_TypeCode anon_subtypes_array19[] =
   { (CORBA_TypeCode) & TC_Evolution_Composer_Recipient_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_Evolution_Composer_Recipient_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array19,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Evolution_Composer_RecipientList_0 == 'E') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_1 == 'v') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_2 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_3 == 'l') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_4 == 'u') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_5 == 't') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_6 == 'i') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_7 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_8 == 'n') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_9 == '_') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_10 == 'C') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_11 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_12 == 'm') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_13 == 'p') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_14 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_15 == 's') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_16 == 'e') \
&& (TC_IMPL_TC_Evolution_Composer_RecipientList_17 == 'r') \
) && !defined(TC_DEF_TC_Evolution_Composer_RecipientList)
#define TC_DEF_TC_Evolution_Composer_RecipientList 1
static const CORBA_TypeCode anon_subtypes_array23[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_Evolution_Composer_Recipient_struct

   };
const struct CORBA_TypeCode_struct TC_Evolution_Composer_RecipientList_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "RecipientList",
      "IDL:Evolution/Composer/RecipientList:1.0",

   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array23,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Evolution_Composer_CouldNotParse_0 == 'E') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_1 == 'v') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_2 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_3 == 'l') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_4 == 'u') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_5 == 't') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_6 == 'i') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_7 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_8 == 'n') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_9 == '_') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_10 == 'C') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_11 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_12 == 'm') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_13 == 'p') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_14 == 'o') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_15 == 's') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_16 == 'e') \
&& (TC_IMPL_TC_Evolution_Composer_CouldNotParse_17 == 'r') \
) && !defined(TC_DEF_TC_Evolution_Composer_CouldNotParse)
#define TC_DEF_TC_Evolution_Composer_CouldNotParse 1
const struct CORBA_TypeCode_struct TC_Evolution_Composer_CouldNotParse_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "CouldNotParse",
      "IDL:Evolution/Composer/CouldNotParse:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
gpointer
Evolution_Composer_Recipient__free(gpointer mem, gpointer dat,
				   CORBA_boolean free_strings)
{
   Evolution_Composer_Recipient *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->name), NULL, free_strings);
   }
   if (free_strings) {
      CORBA_string__free(&(var->address), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

Evolution_Composer_Recipient *
Evolution_Composer_Recipient__alloc(void)
{
   Evolution_Composer_Recipient *retval;

   retval =
      ORBit_alloc(sizeof(Evolution_Composer_Recipient),
		  (ORBit_free_childvals) Evolution_Composer_Recipient__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->name), '\0', sizeof(retval->name));
   memset(&(retval->address), '\0', sizeof(retval->address));
   return retval;
}

#if ( (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_0 == 'E') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_1 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_3 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_4 == 'u') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_5 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_6 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_7 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_8 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_9 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_10 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_11 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_12 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_13 == 'p') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_14 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_15 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_16 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_Evolution_Composer_Recipient_17 == 'r') \
) && !defined(ORBIT_DEF_CORBA_sequence_Evolution_Composer_Recipient)
#define ORBIT_DEF_CORBA_sequence_Evolution_Composer_Recipient 1

gpointer
CORBA_sequence_Evolution_Composer_Recipient__free(gpointer mem, gpointer dat,
						  CORBA_boolean free_strings)
{
   CORBA_sequence_Evolution_Composer_Recipient *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_Evolution_Composer_Recipient *
CORBA_sequence_Evolution_Composer_Recipient__alloc(void)
{
   CORBA_sequence_Evolution_Composer_Recipient *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_Evolution_Composer_Recipient),
		  (ORBit_free_childvals)
		  CORBA_sequence_Evolution_Composer_Recipient__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

Evolution_Composer_Recipient *
CORBA_sequence_Evolution_Composer_Recipient_allocbuf(CORBA_unsigned_long len)
{
   Evolution_Composer_Recipient *retval =
      ORBit_alloc(sizeof(Evolution_Composer_Recipient) * len,
		  (ORBit_free_childvals) Evolution_Composer_Recipient__free,
		  GUINT_TO_POINTER(len));

   memset(retval, '\0', sizeof(Evolution_Composer_Recipient) * len);
   return retval;
}
#endif

gpointer
Evolution_Composer_RecipientList__free(gpointer mem, gpointer dat,
				       CORBA_boolean free_strings)
{
   return CORBA_sequence_Evolution_Composer_Recipient__free(mem, dat,
							    free_strings);
}

Evolution_Composer_RecipientList *
Evolution_Composer_RecipientList__alloc(void)
{
   return CORBA_sequence_Evolution_Composer_Recipient__alloc();
}

gpointer
Evolution_Composer_CouldNotParse__free(gpointer mem, gpointer dat,
				       CORBA_boolean free_strings)
{
   Evolution_Composer_CouldNotParse *var = mem;

   return (gpointer) (var + 1);
}

CORBA_unsigned_long Evolution_Composer__classid = 0;
