/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <glib.h>
#define ORBIT_IDL_SERIAL 9
#include <orb/orbit.h>

#ifndef Evolution_Composer_H
#define Evolution_Composer_H 1
#ifdef __cplusplus
extern "C"
{
#endif				/* __cplusplus */

/** typedefs **/
#include <bonobo/Bonobo.h>
#if !defined(ORBIT_DECL_GNOME_Evolution_Composer) && !defined(_GNOME_Evolution_Composer_defined)
#define ORBIT_DECL_GNOME_Evolution_Composer 1
#define _GNOME_Evolution_Composer_defined 1
#define GNOME_Evolution_Composer__free CORBA_Object__free
   typedef CORBA_Object GNOME_Evolution_Composer;
   extern CORBA_unsigned_long GNOME_Evolution_Composer__classid;
#if !defined(TC_IMPL_TC_GNOME_Evolution_Composer_0)
#define TC_IMPL_TC_GNOME_Evolution_Composer_0 'E'
#define TC_IMPL_TC_GNOME_Evolution_Composer_1 'v'
#define TC_IMPL_TC_GNOME_Evolution_Composer_2 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_3 'l'
#define TC_IMPL_TC_GNOME_Evolution_Composer_4 'u'
#define TC_IMPL_TC_GNOME_Evolution_Composer_5 't'
#define TC_IMPL_TC_GNOME_Evolution_Composer_6 'i'
#define TC_IMPL_TC_GNOME_Evolution_Composer_7 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_8 'n'
#define TC_IMPL_TC_GNOME_Evolution_Composer_9 '_'
#define TC_IMPL_TC_GNOME_Evolution_Composer_10 'C'
#define TC_IMPL_TC_GNOME_Evolution_Composer_11 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_12 'm'
#define TC_IMPL_TC_GNOME_Evolution_Composer_13 'p'
#define TC_IMPL_TC_GNOME_Evolution_Composer_14 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_15 's'
#define TC_IMPL_TC_GNOME_Evolution_Composer_16 'e'
#define TC_IMPL_TC_GNOME_Evolution_Composer_17 'r'
   extern const struct CORBA_TypeCode_struct
      TC_GNOME_Evolution_Composer_struct;
#define TC_GNOME_Evolution_Composer ((CORBA_TypeCode)&TC_GNOME_Evolution_Composer_struct)
#endif
#endif
#if !defined(_GNOME_Evolution_Composer_Recipient_defined)
#define _GNOME_Evolution_Composer_Recipient_defined 1
   typedef struct
   {
      CORBA_char *name;
      CORBA_char *address;
   }
   GNOME_Evolution_Composer_Recipient;

#if !defined(TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_0)
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_0 'E'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_1 'v'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_2 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_3 'l'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_4 'u'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_5 't'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_6 'i'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_7 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_8 'n'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_9 '_'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_10 'C'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_11 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_12 'm'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_13 'p'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_14 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_15 's'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_16 'e'
#define TC_IMPL_TC_GNOME_Evolution_Composer_Recipient_17 'r'
   extern const struct CORBA_TypeCode_struct
      TC_GNOME_Evolution_Composer_Recipient_struct;
#define TC_GNOME_Evolution_Composer_Recipient ((CORBA_TypeCode)&TC_GNOME_Evolution_Composer_Recipient_struct)
#endif
   extern GNOME_Evolution_Composer_Recipient
      *GNOME_Evolution_Composer_Recipient__alloc(void);
   extern gpointer GNOME_Evolution_Composer_Recipient__free(gpointer mem,
							    gpointer dat,
							    CORBA_boolean free_strings);	/* ORBit internal use */
#endif
#if !defined(ORBIT_DECL_CORBA_sequence_GNOME_Evolution_Composer_Recipient) && !defined(_CORBA_sequence_GNOME_Evolution_Composer_Recipient_defined)
#define ORBIT_DECL_CORBA_sequence_GNOME_Evolution_Composer_Recipient 1
#define _CORBA_sequence_GNOME_Evolution_Composer_Recipient_defined 1
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_0 'E'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_1 'v'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_2 'o'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_3 'l'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_4 'u'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_5 't'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_6 'i'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_7 'o'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_8 'n'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_9 '_'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_10 'C'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_11 'o'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_12 'm'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_13 'p'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_14 'o'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_15 's'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_16 'e'
#define ORBIT_IMPL_CORBA_sequence_GNOME_Evolution_Composer_Recipient_17 'r'
   typedef struct
   {
      CORBA_unsigned_long _maximum,
       _length;
      GNOME_Evolution_Composer_Recipient *_buffer;
      CORBA_boolean _release;
   }
   CORBA_sequence_GNOME_Evolution_Composer_Recipient;
#if !defined(TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_0)
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_0 'E'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_1 'v'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_2 'o'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_3 'l'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_4 'u'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_5 't'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_6 'i'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_7 'o'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_8 'n'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_9 '_'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_10 'C'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_11 'o'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_12 'm'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_13 'p'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_14 'o'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_15 's'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_16 'e'
#define TC_IMPL_TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_17 'r'
   extern const struct CORBA_TypeCode_struct
      TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_struct;
#define TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient ((CORBA_TypeCode)&TC_CORBA_sequence_GNOME_Evolution_Composer_Recipient_struct)
#endif
   extern CORBA_sequence_GNOME_Evolution_Composer_Recipient
      *CORBA_sequence_GNOME_Evolution_Composer_Recipient__alloc(void);
   extern gpointer
      CORBA_sequence_GNOME_Evolution_Composer_Recipient__free(gpointer mem,
							      gpointer dat,
							      CORBA_boolean free_strings);	/* ORBit internal use */
   GNOME_Evolution_Composer_Recipient
      *CORBA_sequence_GNOME_Evolution_Composer_Recipient_allocbuf
      (CORBA_unsigned_long len);
#endif
#if !defined(_GNOME_Evolution_Composer_RecipientList_defined)
#define _GNOME_Evolution_Composer_RecipientList_defined 1
   typedef CORBA_sequence_GNOME_Evolution_Composer_Recipient
      GNOME_Evolution_Composer_RecipientList;
#if !defined(TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_0)
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_0 'E'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_1 'v'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_2 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_3 'l'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_4 'u'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_5 't'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_6 'i'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_7 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_8 'n'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_9 '_'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_10 'C'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_11 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_12 'm'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_13 'p'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_14 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_15 's'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_16 'e'
#define TC_IMPL_TC_GNOME_Evolution_Composer_RecipientList_17 'r'
   extern const struct CORBA_TypeCode_struct
      TC_GNOME_Evolution_Composer_RecipientList_struct;
#define TC_GNOME_Evolution_Composer_RecipientList ((CORBA_TypeCode)&TC_GNOME_Evolution_Composer_RecipientList_struct)
#endif
   extern GNOME_Evolution_Composer_RecipientList
      *GNOME_Evolution_Composer_RecipientList__alloc(void);
   extern gpointer GNOME_Evolution_Composer_RecipientList__free(gpointer mem,
								gpointer dat,
								CORBA_boolean free_strings);	/* ORBit internal use */
#endif
#define ex_GNOME_Evolution_Composer_CouldNotParse "IDL:GNOME/Evolution/Composer/CouldNotParse:1.0"
   void _ORBIT_GNOME_Evolution_Composer_CouldNotParse_demarshal(GIOPRecvBuffer
								*
								_ORBIT_recv_buffer,
								CORBA_Environment
								* ev);
   void _ORBIT_GNOME_Evolution_Composer_CouldNotParse_marshal(GIOPSendBuffer *
							      _ORBIT_send_buffer,
							      CORBA_Environment
							      * ev);
#if !defined(_GNOME_Evolution_Composer_CouldNotParse_defined)
#define _GNOME_Evolution_Composer_CouldNotParse_defined 1
   typedef struct
   {
      int dummy;
   }
   GNOME_Evolution_Composer_CouldNotParse;

#if !defined(TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_0)
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_0 'E'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_1 'v'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_2 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_3 'l'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_4 'u'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_5 't'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_6 'i'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_7 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_8 'n'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_9 '_'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_10 'C'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_11 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_12 'm'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_13 'p'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_14 'o'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_15 's'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_16 'e'
#define TC_IMPL_TC_GNOME_Evolution_Composer_CouldNotParse_17 'r'
   extern const struct CORBA_TypeCode_struct
      TC_GNOME_Evolution_Composer_CouldNotParse_struct;
#define TC_GNOME_Evolution_Composer_CouldNotParse ((CORBA_TypeCode)&TC_GNOME_Evolution_Composer_CouldNotParse_struct)
#endif
#define GNOME_Evolution_Composer_CouldNotParse__alloc() NULL
   extern gpointer GNOME_Evolution_Composer_CouldNotParse__free(gpointer mem,
								gpointer dat,
								CORBA_boolean free_strings);	/* ORBit internal use */
#endif

/** POA structures **/
   typedef struct
   {
      void *_private;
      void (*setHeaders) (PortableServer_Servant _servant,
			  const GNOME_Evolution_Composer_RecipientList * to,
			  const GNOME_Evolution_Composer_RecipientList * cc,
			  const GNOME_Evolution_Composer_RecipientList * bcc,
			  const CORBA_char * subject, CORBA_Environment * ev);
      void (*setBodyText) (PortableServer_Servant _servant,
			   const CORBA_char * body, CORBA_Environment * ev);
      void (*attachMIME) (PortableServer_Servant _servant,
			  const CORBA_char * data, CORBA_Environment * ev);
      void (*attachData) (PortableServer_Servant _servant,
			  const CORBA_char * content_type,
			  const CORBA_char * filename,
			  const CORBA_char * description,
			  const CORBA_boolean show_inline,
			  const CORBA_char * data, CORBA_Environment * ev);
      void (*show) (PortableServer_Servant _servant, CORBA_Environment * ev);
   }
   POA_GNOME_Evolution_Composer__epv;
   typedef struct
   {
      PortableServer_ServantBase__epv *_base_epv;
      POA_Bonobo_Unknown__epv *Bonobo_Unknown_epv;
      POA_GNOME_Evolution_Composer__epv *GNOME_Evolution_Composer_epv;
   }
   POA_GNOME_Evolution_Composer__vepv;
   typedef struct
   {
      void *_private;
      POA_GNOME_Evolution_Composer__vepv *vepv;
   }
   POA_GNOME_Evolution_Composer;
   extern void POA_GNOME_Evolution_Composer__init(PortableServer_Servant
						  servant,
						  CORBA_Environment * ev);
   extern void POA_GNOME_Evolution_Composer__fini(PortableServer_Servant
						  servant,
						  CORBA_Environment * ev);

/** prototypes **/
#define GNOME_Evolution_Composer_ref Bonobo_Unknown_ref
#define GNOME_Evolution_Composer_unref Bonobo_Unknown_unref
#define GNOME_Evolution_Composer_queryInterface Bonobo_Unknown_queryInterface
   void GNOME_Evolution_Composer_setHeaders(GNOME_Evolution_Composer _obj,
					    const
					    GNOME_Evolution_Composer_RecipientList
					    * to,
					    const
					    GNOME_Evolution_Composer_RecipientList
					    * cc,
					    const
					    GNOME_Evolution_Composer_RecipientList
					    * bcc, const CORBA_char * subject,
					    CORBA_Environment * ev);
   void GNOME_Evolution_Composer_setBodyText(GNOME_Evolution_Composer _obj,
					     const CORBA_char * body,
					     CORBA_Environment * ev);
   void GNOME_Evolution_Composer_attachMIME(GNOME_Evolution_Composer _obj,
					    const CORBA_char * data,
					    CORBA_Environment * ev);
   void GNOME_Evolution_Composer_attachData(GNOME_Evolution_Composer _obj,
					    const CORBA_char * content_type,
					    const CORBA_char * filename,
					    const CORBA_char * description,
					    const CORBA_boolean show_inline,
					    const CORBA_char * data,
					    CORBA_Environment * ev);
   void GNOME_Evolution_Composer_show(GNOME_Evolution_Composer _obj,
				      CORBA_Environment * ev);

   void
      _ORBIT_skel_GNOME_Evolution_Composer_setHeaders
      (POA_GNOME_Evolution_Composer * _ORBIT_servant,
       GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev,
       void (*_impl_setHeaders) (PortableServer_Servant _servant,
				 const GNOME_Evolution_Composer_RecipientList
				 * to,
				 const GNOME_Evolution_Composer_RecipientList
				 * cc,
				 const GNOME_Evolution_Composer_RecipientList
				 * bcc, const CORBA_char * subject,
				 CORBA_Environment * ev));
   void
      _ORBIT_skel_GNOME_Evolution_Composer_setBodyText
      (POA_GNOME_Evolution_Composer * _ORBIT_servant,
       GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev,
       void (*_impl_setBodyText) (PortableServer_Servant _servant,
				  const CORBA_char * body,
				  CORBA_Environment * ev));
   void
      _ORBIT_skel_GNOME_Evolution_Composer_attachMIME
      (POA_GNOME_Evolution_Composer * _ORBIT_servant,
       GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev,
       void (*_impl_attachMIME) (PortableServer_Servant _servant,
				 const CORBA_char * data,
				 CORBA_Environment * ev));
   void
      _ORBIT_skel_GNOME_Evolution_Composer_attachData
      (POA_GNOME_Evolution_Composer * _ORBIT_servant,
       GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev,
       void (*_impl_attachData) (PortableServer_Servant _servant,
				 const CORBA_char * content_type,
				 const CORBA_char * filename,
				 const CORBA_char * description,
				 const CORBA_boolean show_inline,
				 const CORBA_char * data,
				 CORBA_Environment * ev));
   void _ORBIT_skel_GNOME_Evolution_Composer_show(POA_GNOME_Evolution_Composer
						  * _ORBIT_servant,
						  GIOPRecvBuffer *
						  _ORBIT_recv_buffer,
						  CORBA_Environment * ev,
						  void (*_impl_show)
						  (PortableServer_Servant
						   _servant,
						   CORBA_Environment * ev));
#ifdef __cplusplus
}
#endif				/* __cplusplus */

#endif
#undef ORBIT_IDL_SERIAL
