/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "Evolution-Composer.h"

void
_ORBIT_skel_Evolution_Composer_set_headers(POA_Evolution_Composer *
					   _ORBIT_servant,
					   GIOPRecvBuffer *
					   _ORBIT_recv_buffer,
					   CORBA_Environment * ev,
					   void (*_impl_set_headers)
					   (PortableServer_Servant _servant,
					    const
					    Evolution_Composer_RecipientList *
					    to,
					    const
					    Evolution_Composer_RecipientList *
					    cc,
					    const
					    Evolution_Composer_RecipientList *
					    bcc, const CORBA_char * subject,
					    CORBA_Environment * ev))
{
   Evolution_Composer_RecipientList to = { 0, 0, NULL, CORBA_FALSE };
   Evolution_Composer_RecipientList cc = { 0, 0, NULL, CORBA_FALSE };
   Evolution_Composer_RecipientList bcc = { 0, 0, NULL, CORBA_FALSE };
   CORBA_char *subject;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_17;
      register CORBA_unsigned_long _ORBIT_tmpvar_18;
      CORBA_unsigned_long _ORBIT_tmpvar_19;
      register CORBA_unsigned_long _ORBIT_tmpvar_20;
      CORBA_unsigned_long _ORBIT_tmpvar_21;
      register CORBA_unsigned_long _ORBIT_tmpvar_22;
      register CORBA_unsigned_long _ORBIT_tmpvar_23;
      CORBA_unsigned_long _ORBIT_tmpvar_24;
      register CORBA_unsigned_long _ORBIT_tmpvar_25;
      CORBA_unsigned_long _ORBIT_tmpvar_26;
      register CORBA_unsigned_long _ORBIT_tmpvar_27;
      register CORBA_unsigned_long _ORBIT_tmpvar_28;
      CORBA_unsigned_long _ORBIT_tmpvar_29;
      register CORBA_unsigned_long _ORBIT_tmpvar_30;
      CORBA_unsigned_long _ORBIT_tmpvar_31;
      register CORBA_unsigned_long _ORBIT_tmpvar_32;
      CORBA_unsigned_long _ORBIT_tmpvar_33;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (to._length))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	 to._buffer =
	    alloca(sizeof(to._buffer[_ORBIT_tmpvar_17]) * to._length);
	 to._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_17 = 0; _ORBIT_tmpvar_17 < to._length;
	      _ORBIT_tmpvar_17++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    
	       (*((guint32 *) & (_ORBIT_tmpvar_19))) =
	       GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	    to._buffer[_ORBIT_tmpvar_17].name = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(to._buffer[_ORBIT_tmpvar_17].name[_ORBIT_tmpvar_18]) *
	       _ORBIT_tmpvar_19;
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    
	       (*((guint32 *) & (_ORBIT_tmpvar_21))) =
	       GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	    to._buffer[_ORBIT_tmpvar_17].address = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(to._buffer[_ORBIT_tmpvar_17].
		      address[_ORBIT_tmpvar_20]) * _ORBIT_tmpvar_21;
	 }

	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (cc._length))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	 cc._buffer =
	    alloca(sizeof(cc._buffer[_ORBIT_tmpvar_22]) * cc._length);
	 cc._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_22 = 0; _ORBIT_tmpvar_22 < cc._length;
	      _ORBIT_tmpvar_22++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    
	       (*((guint32 *) & (_ORBIT_tmpvar_24))) =
	       GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	    cc._buffer[_ORBIT_tmpvar_22].name = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(cc._buffer[_ORBIT_tmpvar_22].name[_ORBIT_tmpvar_23]) *
	       _ORBIT_tmpvar_24;
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    
	       (*((guint32 *) & (_ORBIT_tmpvar_26))) =
	       GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	    cc._buffer[_ORBIT_tmpvar_22].address = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(cc._buffer[_ORBIT_tmpvar_22].
		      address[_ORBIT_tmpvar_25]) * _ORBIT_tmpvar_26;
	 }

	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (bcc._length))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	 bcc._buffer =
	    alloca(sizeof(bcc._buffer[_ORBIT_tmpvar_27]) * bcc._length);
	 bcc._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_27 = 0; _ORBIT_tmpvar_27 < bcc._length;
	      _ORBIT_tmpvar_27++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    
	       (*((guint32 *) & (_ORBIT_tmpvar_29))) =
	       GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	    bcc._buffer[_ORBIT_tmpvar_27].name = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(bcc._buffer[_ORBIT_tmpvar_27].name[_ORBIT_tmpvar_28]) *
	       _ORBIT_tmpvar_29;
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    
	       (*((guint32 *) & (_ORBIT_tmpvar_31))) =
	       GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	    bcc._buffer[_ORBIT_tmpvar_27].address = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(bcc._buffer[_ORBIT_tmpvar_27].
		      address[_ORBIT_tmpvar_30]) * _ORBIT_tmpvar_31;
	 }

	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_33))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 subject = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(subject[_ORBIT_tmpvar_32]) * _ORBIT_tmpvar_33;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 to._length = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 to._buffer =
	    alloca(sizeof(to._buffer[_ORBIT_tmpvar_17]) * to._length);
	 to._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_17 = 0; _ORBIT_tmpvar_17 < to._length;
	      _ORBIT_tmpvar_17++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    _ORBIT_tmpvar_19 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	    _ORBIT_curptr += 4;
	    to._buffer[_ORBIT_tmpvar_17].name = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(to._buffer[_ORBIT_tmpvar_17].name[_ORBIT_tmpvar_18]) *
	       _ORBIT_tmpvar_19;
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    _ORBIT_tmpvar_21 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	    _ORBIT_curptr += 4;
	    to._buffer[_ORBIT_tmpvar_17].address = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(to._buffer[_ORBIT_tmpvar_17].
		      address[_ORBIT_tmpvar_20]) * _ORBIT_tmpvar_21;
	 }

	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 cc._length = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 cc._buffer =
	    alloca(sizeof(cc._buffer[_ORBIT_tmpvar_22]) * cc._length);
	 cc._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_22 = 0; _ORBIT_tmpvar_22 < cc._length;
	      _ORBIT_tmpvar_22++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    _ORBIT_tmpvar_24 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	    _ORBIT_curptr += 4;
	    cc._buffer[_ORBIT_tmpvar_22].name = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(cc._buffer[_ORBIT_tmpvar_22].name[_ORBIT_tmpvar_23]) *
	       _ORBIT_tmpvar_24;
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    _ORBIT_tmpvar_26 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	    _ORBIT_curptr += 4;
	    cc._buffer[_ORBIT_tmpvar_22].address = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(cc._buffer[_ORBIT_tmpvar_22].
		      address[_ORBIT_tmpvar_25]) * _ORBIT_tmpvar_26;
	 }

	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 bcc._length = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 bcc._buffer =
	    alloca(sizeof(bcc._buffer[_ORBIT_tmpvar_27]) * bcc._length);
	 bcc._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_27 = 0; _ORBIT_tmpvar_27 < bcc._length;
	      _ORBIT_tmpvar_27++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    _ORBIT_tmpvar_29 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	    _ORBIT_curptr += 4;
	    bcc._buffer[_ORBIT_tmpvar_27].name = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(bcc._buffer[_ORBIT_tmpvar_27].name[_ORBIT_tmpvar_28]) *
	       _ORBIT_tmpvar_29;
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    _ORBIT_tmpvar_31 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	    _ORBIT_curptr += 4;
	    bcc._buffer[_ORBIT_tmpvar_27].address = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(bcc._buffer[_ORBIT_tmpvar_27].
		      address[_ORBIT_tmpvar_30]) * _ORBIT_tmpvar_31;
	 }

	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_33 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 subject = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(subject[_ORBIT_tmpvar_32]) * _ORBIT_tmpvar_33;
      }
   }
   _impl_set_headers(_ORBIT_servant, &(to), &(cc), &(bcc), subject, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Evolution_Composer_set_body_text(POA_Evolution_Composer *
					     _ORBIT_servant,
					     GIOPRecvBuffer *
					     _ORBIT_recv_buffer,
					     CORBA_Environment * ev,
					     void (*_impl_set_body_text)
					     (PortableServer_Servant _servant,
					      const CORBA_char * body,
					      CORBA_Environment * ev))
{
   CORBA_char *body;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 body = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(body[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 body = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(body[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_set_body_text(_ORBIT_servant, body, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_Evolution_Composer_CouldNotParse_marshal(GIOPSendBuffer *
						_ORBIT_send_buffer,
						CORBA_Environment * ev)
{
}
void
_ORBIT_skel_Evolution_Composer_attach_MIME(POA_Evolution_Composer *
					   _ORBIT_servant,
					   GIOPRecvBuffer *
					   _ORBIT_recv_buffer,
					   CORBA_Environment * ev,
					   void (*_impl_attach_MIME)
					   (PortableServer_Servant _servant,
					    const CORBA_char * data,
					    CORBA_Environment * ev))
{
   CORBA_char *data;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 data = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(data[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 data = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(data[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_attach_MIME(_ORBIT_servant, data, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else if (ev->_major == CORBA_USER_EXCEPTION) {
	    static const ORBit_exception_marshal_info _ORBIT_user_exceptions[]
	       = { {(const CORBA_TypeCode)
		    &TC_Evolution_Composer_CouldNotParse_struct,
		    (gpointer)
		    _ORBIT_Evolution_Composer_CouldNotParse_marshal},
	       {CORBA_OBJECT_NIL, NULL} };

	    ORBit_send_user_exception(_ORBIT_send_buffer, ev,
				      _ORBIT_user_exceptions);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Evolution_Composer_attach_data(POA_Evolution_Composer *
					   _ORBIT_servant,
					   GIOPRecvBuffer *
					   _ORBIT_recv_buffer,
					   CORBA_Environment * ev,
					   void (*_impl_attach_data)
					   (PortableServer_Servant _servant,
					    const CORBA_char * content_type,
					    const CORBA_char * filename,
					    const CORBA_char * description,
					    const CORBA_boolean show_inline,
					    const CORBA_char * data,
					    CORBA_Environment * ev))
{
   CORBA_char *content_type;
   CORBA_char *filename;
   CORBA_char *description;
   CORBA_boolean show_inline;
   CORBA_char *data;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_8;
      CORBA_unsigned_long _ORBIT_tmpvar_9;
      register CORBA_unsigned_long _ORBIT_tmpvar_10;
      CORBA_unsigned_long _ORBIT_tmpvar_11;
      register CORBA_unsigned_long _ORBIT_tmpvar_12;
      CORBA_unsigned_long _ORBIT_tmpvar_13;
      register CORBA_unsigned_long _ORBIT_tmpvar_14;
      CORBA_unsigned_long _ORBIT_tmpvar_15;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_9))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 content_type = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(content_type[_ORBIT_tmpvar_8]) * _ORBIT_tmpvar_9;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_11))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 filename = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(filename[_ORBIT_tmpvar_10]) * _ORBIT_tmpvar_11;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_13))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 description = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(description[_ORBIT_tmpvar_12]) * _ORBIT_tmpvar_13;
	 show_inline = *((CORBA_boolean *) _ORBIT_curptr);
	 _ORBIT_curptr += 1;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_15))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 data = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(data[_ORBIT_tmpvar_14]) * _ORBIT_tmpvar_15;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_9 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 content_type = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(content_type[_ORBIT_tmpvar_8]) * _ORBIT_tmpvar_9;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_11 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 filename = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(filename[_ORBIT_tmpvar_10]) * _ORBIT_tmpvar_11;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_13 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 description = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(description[_ORBIT_tmpvar_12]) * _ORBIT_tmpvar_13;
	 show_inline = *((CORBA_boolean *) _ORBIT_curptr);
	 _ORBIT_curptr += 1;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_15 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 data = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(data[_ORBIT_tmpvar_14]) * _ORBIT_tmpvar_15;
      }
   }
   _impl_attach_data(_ORBIT_servant, content_type, filename, description,
		     show_inline, data, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Evolution_Composer_show(POA_Evolution_Composer * _ORBIT_servant,
				    GIOPRecvBuffer * _ORBIT_recv_buffer,
				    CORBA_Environment * ev,
				    void (*_impl_show) (PortableServer_Servant
							_servant,
							CORBA_Environment *
							ev))
{
   _impl_show(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
static ORBitSkeleton
get_skel_Evolution_Composer(POA_Evolution_Composer * servant,
			    GIOPRecvBuffer * _ORBIT_recv_buffer,
			    gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'a':
	switch (opname[1]) {
	  case 't':
	     switch (opname[2]) {
	       case 't':
		  switch (opname[3]) {
		    case 'a':
		       switch (opname[4]) {
			 case 'c':
			    switch (opname[5]) {
			      case 'h':
				 switch (opname[6]) {
				   case '_':
				      switch (opname[7]) {
					case 'M':
					   if (strcmp((opname + 8), "IME"))
					      break;
					   *impl =
					      (gpointer) servant->vepv->
					      Evolution_Composer_epv->
					      attach_MIME;
					   return (ORBitSkeleton)
					      _ORBIT_skel_Evolution_Composer_attach_MIME;
					   break;
					case 'd':
					   if (strcmp((opname + 8), "ata"))
					      break;
					   *impl =
					      (gpointer) servant->vepv->
					      Evolution_Composer_epv->
					      attach_data;
					   return (ORBitSkeleton)
					      _ORBIT_skel_Evolution_Composer_attach_data;
					   break;
					default:
					   break;
				      }
				      break;
				   default:
				      break;
				 }
				 break;
			      default:
				 break;
			    }
			    break;
			 default:
			    break;
		       }
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'q':
	if (strcmp((opname + 1), "uery_interface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->query_interface;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_query_interface;
	break;
     case 'r':
	if (strcmp((opname + 1), "ef"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_ref;
	break;
     case 's':
	switch (opname[1]) {
	  case 'e':
	     switch (opname[2]) {
	       case 't':
		  switch (opname[3]) {
		    case '_':
		       switch (opname[4]) {
			 case 'b':
			    if (strcmp((opname + 5), "ody_text"))
			       break;
			    *impl =
			       (gpointer) servant->vepv->
			       Evolution_Composer_epv->set_body_text;
			    return (ORBitSkeleton)
			       _ORBIT_skel_Evolution_Composer_set_body_text;
			    break;
			 case 'h':
			    if (strcmp((opname + 5), "eaders"))
			       break;
			    *impl =
			       (gpointer) servant->vepv->
			       Evolution_Composer_epv->set_headers;
			    return (ORBitSkeleton)
			       _ORBIT_skel_Evolution_Composer_set_headers;
			    break;
			 default:
			    break;
		       }
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  case 'h':
	     if (strcmp((opname + 2), "ow"))
		break;
	     *impl = (gpointer) servant->vepv->Evolution_Composer_epv->show;
	     return (ORBitSkeleton) _ORBIT_skel_Evolution_Composer_show;
	     break;
	  default:
	     break;
	}
	break;
     case 'u':
	if (strcmp((opname + 1), "nref"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_unref;
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_Evolution_Composer(CORBA_Object obj,
				     POA_Evolution_Composer * servant)
{
   obj->vepv[Bonobo_Unknown__classid] = servant->vepv->Bonobo_Unknown_epv;
   obj->vepv[Evolution_Composer__classid] =
      servant->vepv->Evolution_Composer_epv;
}

void
POA_Evolution_Composer__init(PortableServer_Servant servant,
			     CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Evolution_Composer,
	 "IDL:Evolution/Composer:1.0",
	 (ORBit_local_objref_init) & init_local_objref_Evolution_Composer };

   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Evolution_Composer__classid)
      Evolution_Composer__classid = ORBit_register_class(&class_info);
}

void
POA_Evolution_Composer__fini(PortableServer_Servant servant,
			     CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}
