/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Go To Date");
gchar *s = N_("Go To Today");
gchar *s = N_("January\n"
              "February\n"
              "March\n"
              "April\n"
              "May\n"
              "June\n"
              "July\n"
              "August\n"
              "September\n"
              "October\n"
              "November\n"
              "December\n"
              "");
