/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Go To Date");
gchar *s = N_("Go To Today");
gchar *s = N_("January");
gchar *s = N_("February");
gchar *s = N_("March");
gchar *s = N_("April");
gchar *s = N_("May");
gchar *s = N_("June");
gchar *s = N_("July");
gchar *s = N_("August");
gchar *s = N_("September");
gchar *s = N_("October");
gchar *s = N_("November");
gchar *s = N_("December");
