/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Recipient list:");
gchar *s = N_("Name:");
gchar *s = N_("Search...");
gchar *s = N_("Name");
gchar *s = N_("Address");
gchar *s = N_("Properties...");
gchar *s = N_("Add...");
gchar *s = N_("To: >>");
gchar *s = N_("Cc: >>");
gchar *s = N_("Bcc: >>");
gchar *s = N_("label9");
gchar *s = N_("label7");
gchar *s = N_("label8");
