/*
 * Translatable strings file generated by extract-ui.
 * Add this file to your project's POTFILES.in
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Attachment properties");
gchar *s = N_("Description:");
gchar *s = N_("File name:");
gchar *s = N_("MIME type:");
