#!/bin/sh
# FIXME: Sigh, we need a less gross way of doing this.

sysname=`uname -s`

if [ "$sysname" = "SunOS" ]; then
	killcmd="pkill"
else
	killcmd="killall"
fi
   
$killcmd -9 wombat 2>/dev/null
$killcmd -9 lt-wombat 2>/dev/null

$killcmd -9 evolution-addressbook 2>/dev/null
$killcmd -9 evolution-addres 2>/dev/null
$killcmd -9 lt-evolution-addressbook 2>/dev/null
$killcmd -9 lt-evolution-add 2>/dev/null

$killcmd -9 evolution-calendar 2>/dev/null
$killcmd -9 evolution-calend 2>/dev/null
$killcmd -9 lt-evolution-calendar 2>/dev/null
$killcmd -9 lt-evolution-cal 2>/dev/null
$killcmd -9 lt-gnomecal 2>/dev/null

$killcmd -9 evolution-mail 2>/dev/null
$killcmd -9 lt-evolution-mail 2>/dev/null
$killcmd -9 lt-evolution-mai 2>/dev/null

$killcmd -9 evolution-executive-summary 2>/dev/null
$killcmd -9 evolution-execut 2>/dev/null
$killcmd -9 lt-evolution-executive-summary 2>/dev/null
$killcmd -9 lt-evolution-exe 2>/dev/null

$killcmd -9 evolution 2>/dev/null

$killcmd -9 rdf-summary 2>/dev/null
$killcmd -9 lt-rdf-summary 2>/dev/null

$killcmd -9 evolution-elm-importer 2>/dev/null
$killcmd -9 evolution-elm-im 2>/dev/null
$killcmd -9 evolution-pine-importer 2>/dev/null
$killcmd -9 evolution-pine-i 2>/dev/null
$killcmd -9 evolution-netscape-importer 2>/dev/null
$killcmd -9 evolution-netsca 2>/dev/null
$killcmd -9 evolution-vcard-importer 2>/dev/null
$killcmd -9 evolution-vcard- 2>/dev/null
$killcmd -9 evolution-ldif-importer 2>/dev/null
$killcmd -9 evolution-ldif-i 2>/dev/null

$killcmd -9 evolution-alarm-notify 2>/dev/null
$killcmd -9 evolution-alarm- 2>/dev/null

$killcmd -9 lt-gnome-spell-component 2>/dev/null
$killcmd -9 lt-gnome-spell-c 2>/dev/null
$killcmd -9 gnome-spell-component 2>/dev/null
$killcmd -9 gnome-spell-comp 2>/dev/null

$killcmd -9 lt-gnome-gtkhtml-editor 2>/dev/null
$killcmd -9 lt-gnome-gtkhtml 2>/dev/null
$killcmd -9 gnome-gtkhtml-editor 2>/dev/null
$killcmd -9 gnome-gtkhtml-ed 2>/dev/null

$killcmd -9 lt-bonobo-moniker-xmldb 2>/dev/null
$killcmd -9 lt-bonobo-monike 2>/dev/null
$killcmd -9 bonobo-moniker-xmldb 2>/dev/null
$killcmd -9 bonobo-moniker-x 2>/dev/null

