/*
 *  This file is autogenerated from evolution-subscribe.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("_File");
gchar *s = N_("Close");
gchar *s = N_("_Edit");
gchar *s = N_("Select _All");
gchar *s = N_("_Unselect All");
gchar *s = N_("F_older");
gchar *s = N_("Subscribe");
gchar *s = N_("Unsubscribe");
gchar *s = N_("Subscribe");
gchar *s = N_("Add folder to your list of subscribed folders");
gchar *s = N_("Unsubscribe");
gchar *s = N_("Remove folder from your list of subscribed folders");
gchar *s = N_("Refresh List");
gchar *s = N_("Refresh List of Folders");
