/*
 *  This file is autogenerated from evolution.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("Show the _Shortcut Bar");
gchar *s = N_("Toggle whether to show the shortcut bar");
gchar *s = N_("Show the _Folder Bar");
gchar *s = N_("Toggle whether to show the folder bar");
gchar *s = N_("_File");
gchar *s = N_("_New");
gchar *s = N_("_View");
gchar *s = N_("_Folder");
gchar *s = N_("Evolution bar _shortcut");
gchar *s = N_("_Mail message (FIXME)");
gchar *s = N_("_Appointment (FIXME)");
gchar *s = N_("_Contact (FIXME)");
gchar *s = N_("_Task (FIXME)");
gchar *s = N_("_Go to Folder...");
gchar *s = N_("Display a different folder");
gchar *s = N_("_Create New Folder...");
gchar *s = N_("Create a new folder");
gchar *s = N_("E_xit");
gchar *s = N_("Exit the program");
gchar *s = N_("_Edit");
gchar *s = N_("_View");
gchar *s = N_("_Settings");
gchar *s = N_("_Help");
gchar *s = N_("_Index");
gchar *s = N_("Getting _Started");
gchar *s = N_("Using the _Mailer");
gchar *s = N_("Using the _Calendar");
gchar *s = N_("Using the C_ontact Manager");
gchar *s = N_("_Submit Bug Report");
gchar *s = N_("Submit bug report using Bug Buddy");
gchar *s = N_("_About Evolution...");
gchar *s = N_("Show information about Evolution");
