/*
 *  This file is autogenerated from evolution-executive-summary.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("Add Service");
gchar *s = N_("Add a new service to the Executive Summary");
