/*
 *  This file is autogenerated from evolution-calendar.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("_New");
gchar *s = N_("New Ca_lendar");
gchar *s = N_("Create a new calendar");
gchar *s = N_("_Open");
gchar *s = N_("_Open Calendar");
gchar *s = N_("Open a calendar");
gchar *s = N_("_Save Calendar As");
gchar *s = N_("Save calendar As something else");
gchar *s = N_("_Print this calendar");
gchar *s = N_("_New appointment...");
gchar *s = N_("Create a new appointment");
gchar *s = N_("Calendar Preferences...");
gchar *s = N_("Alter preferences");
gchar *s = N_("New");
gchar *s = N_("Create a new appointment");
gchar *s = N_("Print");
gchar *s = N_("Print this calendar");
gchar *s = N_("Prev");
gchar *s = N_("Go back in time");
gchar *s = N_("Today");
gchar *s = N_("Go to present time");
gchar *s = N_("Next");
gchar *s = N_("Go forward in time");
gchar *s = N_("Go to");
gchar *s = N_("Go to a specific date");
gchar *s = N_("Day");
gchar *s = N_("Show 1 day");
gchar *s = N_("5 Days");
gchar *s = N_("Show the working week");
gchar *s = N_("Week");
gchar *s = N_("Show 1 week");
gchar *s = N_("Month");
gchar *s = N_("Show 1 month");
