/*
 *  This file is autogenerated from evolution-addressbook-ldap.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("N_ew Directory Server");
gchar *s = N_("_Actions");
