/*
 *  This file is autogenerated from evolution-mail.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("Compose");
gchar *s = N_("Compose a new message");
gchar *s = N_("Copy");
gchar *s = N_("Copy message to a new folder");
gchar *s = N_("Delete");
gchar *s = N_("Delete this message");
gchar *s = N_("F_older");
gchar *s = N_("Fi_lter on Sender");
gchar *s = N_("Filter on Rec_ipients");
gchar *s = N_("Forget _Passwords");
gchar *s = N_("Forward");
gchar *s = N_("Forward this message");
gchar *s = N_("Get Mail");
gchar *s = N_("Mail _Filters...");
gchar *s = N_("Manage Subscriptions...");
gchar *s = N_("Mar_k As Read");
gchar *s = N_("Mark As U_nread");
gchar *s = N_("Move");
gchar *s = N_("Move message to a new folder");
gchar *s = N_("Previews the message to be printed");
gchar *s = N_("Print");
gchar *s = N_("Print Preview of message...");
gchar *s = N_("Print message to the printer");
gchar *s = N_("Print message...");
gchar *s = N_("Print the selected message");
gchar *s = N_("Reply");
gchar *s = N_("Reply to All");
gchar *s = N_("Reply to _All");
gchar *s = N_("Reply to _Sender");
gchar *s = N_("Reply to all recipients of this message");
gchar *s = N_("Reply to the sender of this message");
gchar *s = N_("Select _All");
gchar *s = N_("Send queued mail and retrieve new mail");
gchar *s = N_("Threaded Message list");
gchar *s = N_("VFolder on Se_nder");
gchar *s = N_("VFolder on _Recipients");
gchar *s = N_("_Apply Filters");
gchar *s = N_("_Configure Folder");
gchar *s = N_("_Copy to Folder");
gchar *s = N_("_Delete");
gchar *s = N_("_Edit Message");
gchar *s = N_("_Expunge");
gchar *s = N_("_Filter on Subject");
gchar *s = N_("_Forward");
gchar *s = N_("_Invert Selection");
gchar *s = N_("_Mail Configuration...");
gchar *s = N_("_Message");
gchar *s = N_("_Move to Folder");
gchar *s = N_("_Open in New Window");
gchar *s = N_("_Print Message");
gchar *s = N_("_Threaded");
gchar *s = N_("_VFolder on Subject");
gchar *s = N_("_Virtual Folder Editor...");
