/*
 *  This file is autogenerated from evolution-contact-editor.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("_File");
gchar *s = N_("_Save");
gchar *s = N_("Save _As");
gchar *s = N_("Delete");
gchar *s = N_("_Print");
gchar *s = N_("Close");
gchar *s = N_("Save and Close");
gchar *s = N_("Save the contact and close the dialog box");
gchar *s = N_("Print...");
gchar *s = N_("Print this item");
gchar *s = N_("Delete");
gchar *s = N_("Delete this item");
