/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("Available fields");
gchar *s = N_("label1");
gchar *s = N_("Show in this order");
gchar *s = N_("label2");
gchar *s = N_("Add >>");
gchar *s = N_("<< Remove");
