/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Show Fields");
gchar *s = N_("A_vailable Fields:");
gchar *s = N_("Sh_ow these fields in order:");
gchar *s = N_("Table HERE");
gchar *s = N_("Table HERE");
gchar *s = N_("Move _Up");
gchar *s = N_("Move _Down");
gchar *s = N_("_Add ->");
gchar *s = N_("<- _Remove");
gchar *s = N_("Group");
gchar *s = N_("Group Items By");
gchar *s = N_("Show field in View");
gchar *s = N_("Ascending");
gchar *s = N_("Descending");
gchar *s = N_("Then By");
gchar *s = N_("Show field in View");
gchar *s = N_("Ascending");
gchar *s = N_("Descending");
gchar *s = N_("Then By");
gchar *s = N_("Show field in View");
gchar *s = N_("Ascending");
gchar *s = N_("Descending");
gchar *s = N_("Then By");
gchar *s = N_("Show field in View");
gchar *s = N_("Ascending");
gchar *s = N_("Descending");
gchar *s = N_("_Clear All");
gchar *s = N_("Sort");
gchar *s = N_("Then By");
gchar *s = N_("Ascending");
gchar *s = N_("Descending");
gchar *s = N_("Then By");
gchar *s = N_("Ascending");
gchar *s = N_("Descending");
gchar *s = N_("Then By");
gchar *s = N_("Ascending");
gchar *s = N_("Descending");
gchar *s = N_("Sort Items By");
gchar *s = N_("Ascending");
gchar *s = N_("Descending");
gchar *s = N_("Clear All");
gchar *s = N_("Description");
gchar *s = N_("_Fields...");
gchar *s = N_("_Sort...");
gchar *s = N_("_Group By...");
gchar *s = N_("label20");
